@@grammar :: mklang
@@whitespace :: /[ \t\r\n]+/

start 
    = { statement } $ ;

statement
    =
    | var_decl
    | cout_stmt
    ;

var_decl
    =
    'var' name:IDENT ':=' expr [ newline ]
    ;

cout_stmt
    =
    'cout' '<<' expr [ newline ]
    ;

expr
    =
    | expr '+' term
    | expr '-' term
    | term
    ;

term
    =
    | term '*' factor
    | term '/' factor
    | factor
    ;

factor
    =
    | '(' expr ')'
    | NUMBER
    | STRING
    | IDENT
    ;

newline = '\n' ;

IDENT = /[A-Za-z_][A-Za-z0-9_]*/ ;
NUMBER = /\d+/ ;
STRING = /"[^"\n]*"/ ;
