// Generated by bootstrap/src/native-js.omg from /tmp/tmp.YI7c7ThJ84/maze_solver.omgb
// Do not edit by hand.

// omg_rt.js — runtime for OMG programs compiled to JavaScript.
//
// Mirrors bootstrap/src/omg_rt.h: provides the value coercion, the
// arithmetic/string ops, and the builtins that AOT-emitted JS calls
// into. Every program transpiled by bootstrap/src/native-js.omg
// inlines this file at the top of its .js output, so the result is
// a single self-contained JS file you can hand to `node` or run in a
// browser.
//
// Value representation:
//   ints    → JS BigInt  (so OMG's i64 semantics survive bitwise ops
//                         past 2^53; arithmetic stays exact)
//   floats  → JS Number  (OMG floats are IEEE-754 f64; same as JS)
//   strings → JS string
//   bools   → JS boolean
//   lists   → JS Array
//   dicts   → JS Map     (preserves insertion order, string keys)
//   none    → null
//   closure → JS function with .__omg_captured marker
//
// We tag the few cases JS can't distinguish on its own (Number vs
// BigInt is the only one that needs care; everything else falls out
// of `typeof`). Most ops accept either int (BigInt) or float
// (Number) and dispatch off `typeof`.

'use strict';

// === Type discrimination ===================================================

function omg_is_int(v)    { return typeof v === 'bigint'; }
function omg_is_float(v)  { return typeof v === 'number'; }
function omg_is_str(v)    { return typeof v === 'string'; }
function omg_is_bool(v)   { return typeof v === 'boolean'; }
function omg_is_list(v)   { return Array.isArray(v); }
function omg_is_dict(v)   { return v instanceof Map; }
function omg_is_none(v)   { return v === null; }
function omg_is_closure(v){ return typeof v === 'function' && v.__omg_captured !== undefined; }

// === Coercion (mirror of omg_as_int / omg_as_double in omg_rt.h) ==========

function omg_as_int(v) {
    if (typeof v === 'bigint') return v;
    if (typeof v === 'boolean') return v ? 1n : 0n;
    if (typeof v === 'number') {
        if (!Number.isFinite(v)) {
            throw new OmgError('ValueError',
                'cannot convert non-finite float to int: ' + v);
        }
        if (v < -9223372036854775808 || v > 9223372036854775807) {
            throw new OmgError('ValueError',
                'float ' + v + ' is outside the i64 range');
        }
        return BigInt(Math.trunc(v));
    }
    if (typeof v === 'string') {
        // Match Rust's Value::as_int and omg_rt.h's omg_as_int:
        // strict integer parse, no whitespace, no junk tail.
        if (!/^-?\d+$/.test(v)) {
            throw new OmgError('TypeError',
                "Invalid literal for int(): '" + v + "'");
        }
        return BigInt(v);
    }
    if (Array.isArray(v)) {
        throw new OmgError('TypeError',
            'cannot convert list to int (use length() instead)');
    }
    if (v instanceof Map) {
        throw new OmgError('TypeError', 'cannot convert dict to int');
    }
    if (v === null) {
        throw new OmgError('TypeError', 'cannot convert none to int');
    }
    if (typeof v === 'function') {
        throw new OmgError('TypeError', 'cannot convert function to int');
    }
    throw new OmgError('TypeError', 'cannot convert value to int');
}

function omg_as_float(v) {
    if (typeof v === 'number') return v;
    if (typeof v === 'bigint') return Number(v);
    if (typeof v === 'boolean') return v ? 1 : 0;
    if (typeof v === 'string') {
        const trimmed = v;
        if (!/^-?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?$/.test(trimmed)) {
            throw new OmgError('TypeError',
                "Invalid literal for float(): '" + v + "'");
        }
        return parseFloat(trimmed);
    }
    if (Array.isArray(v)) {
        throw new OmgError('TypeError', 'cannot convert list to float');
    }
    throw new OmgError('TypeError', 'cannot convert value to float');
}

function omg_truthy(v) {
    if (v === null) return false;
    if (typeof v === 'boolean') return v;
    if (typeof v === 'bigint') return v !== 0n;
    if (typeof v === 'number') return v !== 0;
    if (typeof v === 'string') return v.length > 0;
    if (Array.isArray(v)) return v.length > 0;
    if (v instanceof Map) return v.size > 0;
    return true;
}

// === Errors ================================================================

class OmgError extends Error {
    constructor(kind, message) {
        super(kind + ': ' + message);
        this.kind = kind;
        this.omgMessage = message;
    }
}

function omg_panic(kind, msg) { throw new OmgError(kind, msg); }

// === to_string + emit ======================================================

// Mirrors omg_rt.h's omg_value_to_cstr / omg_print_value. Used by
// `emit` and by string concatenation when one side is non-string.
function omg_to_string(v) {
    if (v === null) return '';
    if (typeof v === 'boolean') return v ? 'true' : 'false';
    if (typeof v === 'string') return v;
    if (typeof v === 'bigint') return v.toString();
    if (typeof v === 'number') {
        // Match OMG's float printing: integer-valued floats print
        // with a trailing ".0", scientific for very small/large.
        if (Number.isFinite(v) && Number.isInteger(v) && Math.abs(v) < 1e16) {
            return v.toFixed(1);
        }
        return v.toString();
    }
    if (Array.isArray(v)) {
        return '[' + v.map(omg_to_string).join(', ') + ']';
    }
    if (v instanceof Map) {
        const parts = [];
        for (const [k, val] of v) parts.push(k + ': ' + omg_to_string(val));
        return '{' + parts.join(', ') + '}';
    }
    if (typeof v === 'function') return '<proc>';
    return String(v);
}

// emit: print to stdout with a trailing newline. In node we use
// console.log which adds the newline; for browser playgrounds we
// override _omg_write to redirect into the page.
let _omg_write = (s) => { console.log(s); };
function omg_emit(v) { _omg_write(omg_to_string(v)); }

// print: same channel, no trailing newline. Used by REPL prompts.
let _omg_print_raw = (s) => { process.stdout.write(s); };
function omg_print(v) {
    if (typeof v !== 'string') {
        omg_panic('TypeError', 'print() expects a string');
    }
    _omg_print_raw(v);
}

// === Stack helper for compound emit ========================================
// (Used by the generated code to manage operand stacks; no-op here
// since we just give programs direct access to a JS array.)

// === Arithmetic ============================================================

function omg_add(a, b) {
    if (typeof a === 'string' || typeof b === 'string') {
        return omg_to_string(a) + omg_to_string(b);
    }
    if (Array.isArray(a) && Array.isArray(b)) {
        return a.concat(b);
    }
    if (typeof a === 'number' || typeof b === 'number') {
        return omg_as_float(a) + omg_as_float(b);
    }
    return omg_as_int(a) + omg_as_int(b);
}

function omg_sub(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        return omg_as_float(a) - omg_as_float(b);
    }
    return omg_as_int(a) - omg_as_int(b);
}

function omg_mul(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        return omg_as_float(a) * omg_as_float(b);
    }
    return omg_as_int(a) * omg_as_int(b);
}

// `/`: any-float → true division (Number). int÷int → floor division
// (BigInt) to match OMG VM (`-7 / 2 == -4`).
function omg_div(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        const bd = omg_as_float(b);
        if (bd === 0) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
        return omg_as_float(a) / bd;
    }
    const x = omg_as_int(a), y = omg_as_int(b);
    if (y === 0n) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
    let q = x / y;
    if ((x % y !== 0n) && ((x < 0n) !== (y < 0n))) q -= 1n;
    return q;
}

function omg_floor_div(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        const bd = omg_as_float(b);
        if (bd === 0) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
        return Math.floor(omg_as_float(a) / bd);
    }
    const x = omg_as_int(a), y = omg_as_int(b);
    if (y === 0n) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
    let q = x / y;
    if ((x % y !== 0n) && ((x < 0n) !== (y < 0n))) q -= 1n;
    return q;
}

function omg_mod(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        const bd = omg_as_float(b);
        if (bd === 0) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
        const ad = omg_as_float(a);
        return ad - Math.floor(ad / bd) * bd;
    }
    const x = omg_as_int(a), y = omg_as_int(b);
    if (y === 0n) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
    let r = x % y;
    if (r !== 0n && ((r < 0n) !== (y < 0n))) r += y;
    return r;
}

function omg_neg(a) {
    if (typeof a === 'number') return -a;
    return -omg_as_int(a);
}

// === Comparisons ===========================================================

function omg_values_equal(a, b) {
    // Cross-type numeric: int↔float compare by value (matches Rust).
    if ((typeof a === 'bigint' && typeof b === 'number') ||
        (typeof a === 'number' && typeof b === 'bigint')) {
        return omg_as_float(a) === omg_as_float(b);
    }
    if (typeof a !== typeof b && !(Array.isArray(a) && Array.isArray(b)) && !(a instanceof Map && b instanceof Map)) {
        return false;
    }
    if (Array.isArray(a) && Array.isArray(b)) {
        if (a.length !== b.length) return false;
        for (let i = 0; i < a.length; i++) {
            if (!omg_values_equal(a[i], b[i])) return false;
        }
        return true;
    }
    if (a instanceof Map && b instanceof Map) {
        if (a.size !== b.size) return false;
        for (const [k, v] of a) {
            if (!b.has(k)) return false;
            if (!omg_values_equal(v, b.get(k))) return false;
        }
        return true;
    }
    return a === b;
}

function omg_eq(a, b) { return omg_values_equal(a, b); }
function omg_ne(a, b) { return !omg_values_equal(a, b); }

function omg_compare(a, b) {
    if (typeof a === 'string' && typeof b === 'string') {
        if (a < b) return -1;
        if (a > b) return 1;
        return 0;
    }
    if (typeof a === 'number' || typeof b === 'number') {
        const x = omg_as_float(a), y = omg_as_float(b);
        if (x < y) return -1;
        if (x > y) return 1;
        return 0;
    }
    const x = omg_as_int(a), y = omg_as_int(b);
    if (x < y) return -1;
    if (x > y) return 1;
    return 0;
}

function omg_lt(a, b) { return omg_compare(a, b) <  0; }
function omg_le(a, b) { return omg_compare(a, b) <= 0; }
function omg_gt(a, b) { return omg_compare(a, b) >  0; }
function omg_ge(a, b) { return omg_compare(a, b) >= 0; }

// === Bitwise ===============================================================

function _reject_float(v, op) {
    if (typeof v === 'number') {
        omg_panic('TypeError', "operator '" + op + "' is not defined for floats");
    }
}

function omg_band(a, b) { _reject_float(a, '&'); _reject_float(b, '&');
                          return omg_as_int(a) & omg_as_int(b); }
function omg_bor (a, b) { _reject_float(a, '|'); _reject_float(b, '|');
                          return omg_as_int(a) | omg_as_int(b); }
function omg_bxor(a, b) { _reject_float(a, '^'); _reject_float(b, '^');
                          return omg_as_int(a) ^ omg_as_int(b); }
function omg_shl (a, b) {
    _reject_float(a, '<<'); _reject_float(b, '<<');
    const ai = omg_as_int(a), bi = omg_as_int(b);
    if (bi < 0n || bi >= 64n) omg_panic('ValueError', 'shift count out of range: ' + bi);
    return BigInt.asIntN(64, ai << bi);
}
function omg_shr (a, b) {
    _reject_float(a, '>>'); _reject_float(b, '>>');
    const ai = omg_as_int(a), bi = omg_as_int(b);
    if (bi < 0n || bi >= 64n) omg_panic('ValueError', 'shift count out of range: ' + bi);
    return ai >> bi;
}
function omg_bnot(a) { _reject_float(a, '~'); return ~omg_as_int(a); }

// === Indexing / slicing ====================================================

function _norm_idx(i, n, what) {
    let r = (i < 0) ? i + BigInt(n) : i;
    if (r < 0n || r >= BigInt(n)) {
        omg_panic('IndexError', 'index ' + i + ' out of range for length ' + n);
    }
    return Number(r);
}

function omg_index(base, idx) {
    if (typeof base === 'string') {
        if (typeof idx !== 'bigint') omg_panic('TypeError', 'string index must be int');
        const r = _norm_idx(idx, base.length, 'string');
        return base[r];
    }
    if (Array.isArray(base)) {
        if (typeof idx !== 'bigint') omg_panic('TypeError', 'list index must be int');
        const r = _norm_idx(idx, base.length, 'list');
        return base[r];
    }
    if (base instanceof Map) {
        const key = (typeof idx === 'string') ? idx : omg_to_string(idx);
        if (!base.has(key)) omg_panic('KeyError', "Key '" + key + "' not found");
        return base.get(key);
    }
    omg_panic('TypeError', 'cannot index value');
}

function omg_index_set(base, idx, val) {
    if (Array.isArray(base)) {
        if (typeof idx !== 'bigint') omg_panic('TypeError', 'list index must be int');
        const r = _norm_idx(idx, base.length, 'list');
        base[r] = val;
        return;
    }
    if (base instanceof Map) {
        const key = (typeof idx === 'string') ? idx : omg_to_string(idx);
        if (base.__omg_frozen) omg_panic('FrozenWriteError', 'Imported modules are read-only');
        base.set(key, val);
        return;
    }
    omg_panic('TypeError', 'cannot assign to index of value');
}

function omg_slice(base, start_v, end_v) {
    let n;
    if (typeof base === 'string') n = base.length;
    else if (Array.isArray(base)) n = base.length;
    else omg_panic('TypeError', 'cannot slice value');

    let start = (start_v === null) ? 0 : Number(omg_as_int(start_v));
    let end   = (end_v   === null) ? n : Number(omg_as_int(end_v));
    if (start < 0) start += n;
    if (end   < 0) end   += n;
    if (start < 0) start = 0;
    if (end   > n) end   = n;
    if (start > end) start = end;
    return base.slice(start, end);
}

function omg_attr(base, name) {
    if (base instanceof Map) {
        if (!base.has(name)) omg_panic('KeyError', "Key '" + name + "' not found");
        return base.get(name);
    }
    omg_panic('TypeError', 'cannot read attribute of value');
}

function omg_attr_set(base, name, val) {
    if (base instanceof Map) {
        if (base.__omg_frozen) omg_panic('FrozenWriteError', 'Imported modules are read-only');
        base.set(name, val);
        return;
    }
    omg_panic('TypeError', 'cannot assign attribute of value');
}

// === Builtins ==============================================================

function omg_length(v) {
    if (typeof v === 'string') {
        // OMG strings are byte-counted? Actually OMG uses code-point
        // count for strings (see omg_rt.h's omg_str_char_count). For
        // ASCII-only text these match; for now just use JS string
        // length which counts UTF-16 code units. Refine if a parity
        // test surfaces a divergence on multi-byte text.
        return BigInt(v.length);
    }
    if (Array.isArray(v)) return BigInt(v.length);
    if (v instanceof Map)  return BigInt(v.size);
    omg_panic('TypeError', 'length() expects a string, list, or dict');
}

function omg_chr(n) {
    const i = Number(omg_as_int(n));
    return String.fromCharCode(i);
}
function omg_ascii(s) {
    if (typeof s !== 'string' || s.length !== 1) {
        omg_panic('TypeError', 'ascii() expects a one-character string');
    }
    return BigInt(s.charCodeAt(0));
}
function omg_int(v)   { return omg_as_int(v); }
function omg_float(v) { return omg_as_float(v); }
function omg_floor(v) { return BigInt(Math.floor(omg_as_float(v))); }
function omg_ceil(v)  { return BigInt(Math.ceil (omg_as_float(v))); }
function omg_round(v) {
    // Banker's rounding to match Rust's f64 round-half-to-even.
    const x = omg_as_float(v);
    const r = Math.round(x);
    if (Math.abs(x - Math.trunc(x)) === 0.5 && (Math.trunc(x) & 1) === 0) {
        return BigInt(r - Math.sign(x));
    }
    return BigInt(r);
}
function omg_abs(v) {
    if (typeof v === 'bigint') return v < 0n ? -v : v;
    if (typeof v === 'number') return Math.abs(v);
    omg_panic('TypeError', 'abs() expects a number');
}
function omg_sqrt(v) { return Math.sqrt(omg_as_float(v)); }
function omg_pow(a, b) {
    if (typeof a === 'bigint' && typeof b === 'bigint' && b >= 0n) {
        return a ** b;
    }
    return Math.pow(omg_as_float(a), omg_as_float(b));
}
function omg_log(v) { return Math.log(omg_as_float(v)); }
function omg_sin(v) { return Math.sin(omg_as_float(v)); }
function omg_cos(v) { return Math.cos(omg_as_float(v)); }
function omg_tan(v) { return Math.tan(omg_as_float(v)); }

function omg_hex(n) {
    let i = omg_as_int(n);
    if (i < 0n) return '-' + (-i).toString(16);
    return i.toString(16);
}
function omg_binary(n, w) {
    let i = omg_as_int(n);
    let s;
    if (i < 0n) s = '-' + (-i).toString(2);
    else s = i.toString(2);
    if (w !== undefined) {
        const width = Number(omg_as_int(w));
        // Pad without sign if positive; if negative we leave as-is
        // (matches OMG which doesn't sign-extend the binary builtin).
        while (s.length < width) s = '0' + s;
    }
    return s;
}

function omg_freeze(d) {
    if (!(d instanceof Map)) omg_panic('TypeError', 'freeze() expects a dict');
    d.__omg_frozen = true;
    return d;
}

function omg_dict_keys(d) {
    if (!(d instanceof Map)) omg_panic('TypeError', 'dict_keys() expects a dict');
    return Array.from(d.keys());
}

function omg_string_bytes(s) {
    if (typeof s !== 'string') omg_panic('TypeError', 'string_bytes() expects a string');
    const enc = new TextEncoder();
    return Array.from(enc.encode(s)).map(b => BigInt(b));
}
function omg_bytes_to_string(bs) {
    if (!Array.isArray(bs)) omg_panic('TypeError', 'bytes_to_string() expects a list of bytes');
    const buf = new Uint8Array(bs.length);
    for (let i = 0; i < bs.length; i++) buf[i] = Number(omg_as_int(bs[i]));
    return new TextDecoder().decode(buf);
}

function omg_float_bits(s) {
    if (typeof s !== 'string') omg_panic('TypeError', 'float_bits() expects a string');
    const f = parseFloat(s);
    const buf = new ArrayBuffer(8);
    new DataView(buf).setFloat64(0, f, true);
    return new DataView(buf).getBigInt64(0, true);
}
function omg_bits_to_float(i) {
    const bi = omg_as_int(i);
    const buf = new ArrayBuffer(8);
    new DataView(buf).setBigInt64(0, bi, true);
    return new DataView(buf).getFloat64(0, true);
}

// === Exit / process control ================================================
// In node these have real implementations; in the browser the
// playground overrides them.

let _omg_exit = (code) => { if (typeof process !== 'undefined') process.exit(Number(code)); };
function omg_exit(code) { _omg_exit(omg_as_int(code)); }
function omg_exit_with_error(msg) {
    if (typeof msg !== 'string') msg = omg_to_string(msg);
    if (typeof process !== 'undefined') {
        process.stderr.write(msg + '\n');
        process.exit(1);
    } else {
        throw new OmgError('Exit', msg);
    }
}
function omg_panic_user(msg) { omg_panic('RuntimeError', omg_to_string(msg)); }

// === File I/O (node-only) =================================================
// In a browser context these all panic with a friendly message; the
// playground can override _omg_fs with a virtual FS if it wants
// programs that touch files to work.

let _omg_fs = null;
if (typeof require !== 'undefined') {
    try { _omg_fs = require('fs'); } catch (_e) { _omg_fs = null; }
}

function _need_fs(name) {
    if (!_omg_fs) {
        omg_panic('TypeError', name + '() requires file I/O (node-only)');
    }
}

function omg_read_file(path) {
    _need_fs('read_file');
    try {
        return _omg_fs.readFileSync(path, 'utf8');
    } catch (_e) {
        return false;
    }
}

function omg_file_exists(path) {
    _need_fs('file_exists');
    return _omg_fs.existsSync(path);
}

function omg_is_dir(path) {
    _need_fs('is_dir');
    try { return _omg_fs.statSync(path).isDirectory(); } catch (_e) { return false; }
}

function omg_read_dir(path) {
    _need_fs('read_dir');
    try {
        return _omg_fs.readdirSync(path).sort().filter(n => n !== '.' && n !== '..');
    } catch (_e) {
        return [];
    }
}

function omg_make_dir(path) {
    _need_fs('make_dir');
    try { _omg_fs.mkdirSync(path, { recursive: true }); return true; }
    catch (_e) { return false; }
}

// File handles for stream I/O. We implement a tiny in-memory buffer
// model (read whole file at open, write to a buffer flushed at close).
// Mode is one of r/rb/w/wb/a/ab/rb+/wb+ — matches omg_rt.h.
const _omg_handles = new Map();
let _omg_next_fd = 1;

function omg_file_open(path, mode) {
    _need_fs('file_open');
    if (typeof path !== 'string' || typeof mode !== 'string') {
        omg_panic('TypeError', 'file_open() expects path and mode');
    }
    const binary = mode.includes('b');
    const fd = _omg_next_fd++;
    let buf;
    if (mode === 'r' || mode === 'rb' || mode === 'rb+') {
        try {
            buf = _omg_fs.readFileSync(path);
        } catch (_e) {
            omg_panic('ValueError', "cannot open '" + path + "': " + _e.message);
        }
    } else if (mode === 'w' || mode === 'wb' || mode === 'wb+') {
        buf = Buffer.alloc(0);
    } else if (mode === 'a' || mode === 'ab') {
        try { buf = _omg_fs.readFileSync(path); } catch (_e) { buf = Buffer.alloc(0); }
    } else {
        omg_panic('ValueError', 'invalid file mode');
    }
    _omg_handles.set(fd, { path, mode, binary, buf, pos: (mode === 'a' || mode === 'ab') ? buf.length : 0 });
    return BigInt(fd);
}

function omg_file_read(handle) {
    const h = _omg_handles.get(Number(omg_as_int(handle)));
    if (!h) omg_panic('ValueError', 'invalid file handle');
    const slice = h.buf.subarray(h.pos);
    h.pos = h.buf.length;
    if (h.binary) return Array.from(slice).map(b => BigInt(b));
    return slice.toString('utf8');
}

function omg_file_write(handle, data) {
    const h = _omg_handles.get(Number(omg_as_int(handle)));
    if (!h) omg_panic('ValueError', 'invalid file handle');
    let chunk;
    if (h.binary) {
        if (!Array.isArray(data)) omg_panic('TypeError', 'file_write() binary handle expects list');
        chunk = Buffer.from(data.map(v => Number(omg_as_int(v))));
    } else {
        if (typeof data !== 'string') omg_panic('TypeError', 'file_write() text handle expects string');
        chunk = Buffer.from(data, 'utf8');
    }
    if (h.pos < h.buf.length) {
        // Overwrite in place, growing if needed.
        const need = h.pos + chunk.length;
        if (need > h.buf.length) {
            const nb = Buffer.alloc(need);
            h.buf.copy(nb, 0, 0, h.buf.length);
            h.buf = nb;
        }
        chunk.copy(h.buf, h.pos);
    } else {
        h.buf = Buffer.concat([h.buf, chunk]);
    }
    h.pos += chunk.length;
    return BigInt(chunk.length);
}

function omg_file_close(handle) {
    const fd = Number(omg_as_int(handle));
    const h = _omg_handles.get(fd);
    if (!h) omg_panic('ValueError', 'invalid file handle');
    if (h.mode !== 'r' && h.mode !== 'rb') {
        try { _omg_fs.writeFileSync(h.path, h.buf); }
        catch (_e) { omg_panic('ValueError', 'cannot write ' + h.path + ': ' + _e.message); }
    }
    _omg_handles.delete(fd);
    return null;
}

function omg_file_seek(handle, offset) {
    const h = _omg_handles.get(Number(omg_as_int(handle)));
    if (!h) omg_panic('ValueError', 'invalid file handle');
    const off = Number(omg_as_int(offset));
    if (off < 0) omg_panic('ValueError', 'file_seek() expects a non-negative offset');
    h.pos = off;
    return BigInt(off);
}

function omg_file_tell(handle) {
    const h = _omg_handles.get(Number(omg_as_int(handle)));
    if (!h) omg_panic('ValueError', 'invalid file handle');
    return BigInt(h.pos);
}

// === Stdin / process control (node-only) =================================

function omg_stdin_readline() {
    if (typeof require === 'undefined') return false;
    // Synchronous one-line stdin read via fs.readFileSync('/dev/stdin').
    // Cached on first call so subsequent calls walk lines from the cache.
    if (!omg_stdin_readline._buf) {
        try {
            omg_stdin_readline._buf = _omg_fs.readFileSync(0, 'utf8');
            omg_stdin_readline._pos = 0;
        } catch (_e) {
            omg_stdin_readline._buf = '';
            omg_stdin_readline._pos = 0;
        }
    }
    const buf = omg_stdin_readline._buf;
    let pos = omg_stdin_readline._pos;
    if (pos >= buf.length) return false;
    const nl = buf.indexOf('\n', pos);
    let line;
    if (nl < 0) { line = buf.slice(pos); omg_stdin_readline._pos = buf.length; }
    else { line = buf.slice(pos, nl); omg_stdin_readline._pos = nl + 1; }
    if (line.endsWith('\r')) line = line.slice(0, -1);
    return line;
}

function omg_stdin_read() {
    if (typeof require === 'undefined') return '';
    try { return _omg_fs.readFileSync(0, 'utf8'); }
    catch (_e) { return ''; }
}

function omg_stdin_read_bytes() {
    if (typeof require === 'undefined') return [];
    try { return Array.from(_omg_fs.readFileSync(0)).map(b => BigInt(b)); }
    catch (_e) { return []; }
}

function omg_subprocess(argv) {
    if (typeof require === 'undefined') {
        omg_panic('TypeError', 'subprocess() requires node');
    }
    const { spawnSync } = require('child_process');
    if (!Array.isArray(argv)) omg_panic('TypeError', 'subprocess() expects a list');
    const cmd = argv[0];
    const args = argv.slice(1);
    const r = spawnSync(cmd, args, { stdio: 'inherit' });
    if (r.error) omg_panic('ValueError', 'subprocess: ' + r.error.message);
    return BigInt(r.status === null ? 128 + (r.signal === 'SIGINT' ? 2 : 1) : r.status);
}

function omg_getpid() {
    return BigInt(typeof process !== 'undefined' ? process.pid : 0);
}

function omg_executable_path() {
    return typeof process !== 'undefined' ? process.argv[0] : false;
}

// === call_builtin: dynamic dispatch =======================================
// Used by some advanced features (the OMG-in-OMG interpreter, error
// helpers). Maps name → handler.

const _omg_builtins = {
    chr: omg_chr,
    ascii: omg_ascii,
    int: omg_int,
    float: omg_float,
    floor: omg_floor,
    ceil: omg_ceil,
    round: omg_round,
    abs: omg_abs,
    sqrt: omg_sqrt,
    pow: omg_pow,
    log: omg_log,
    sin: omg_sin,
    cos: omg_cos,
    tan: omg_tan,
    hex: omg_hex,
    binary: omg_binary,
    length: omg_length,
    freeze: omg_freeze,
    dict_keys: omg_dict_keys,
    string_bytes: omg_string_bytes,
    bytes_to_string: omg_bytes_to_string,
    float_bits: omg_float_bits,
    bits_to_float: omg_bits_to_float,
    panic: omg_panic_user,
    raise: omg_panic_user,
    exit: omg_exit,
    exit_with_error: omg_exit_with_error,
    print: omg_print,
    read_file: omg_read_file,
    file_open: omg_file_open,
    file_read: omg_file_read,
    file_write: omg_file_write,
    file_close: omg_file_close,
    file_seek: omg_file_seek,
    file_tell: omg_file_tell,
    file_exists: omg_file_exists,
    is_dir: omg_is_dir,
    read_dir: omg_read_dir,
    make_dir: omg_make_dir,
    stdin_readline: omg_stdin_readline,
    stdin_read: omg_stdin_read,
    stdin_read_bytes: omg_stdin_read_bytes,
    subprocess: omg_subprocess,
    getpid: omg_getpid,
    executable_path: omg_executable_path,
};

function omg_call_builtin(name, args) {
    const fn = _omg_builtins[name];
    if (!fn) omg_panic('TypeError', 'unknown builtin: ' + name);
    return fn(...args);
}
_omg_builtins.call_builtin = omg_call_builtin;

// === Closure helper =======================================================

function omg_closure(fn, captured) {
    const wrapped = (...args) => fn(captured, ...args);
    wrapped.__omg_captured = captured;
    return wrapped;
}

// String-named function table. Populated by the program preamble
// after every top-level MAKE_FUNC, so that CALL_VALUE on a string
// (which is what import-module dispatch produces) can resolve it.
const omg_func_table = new Map();
function omg_lookup_fn(name) {
    const fn = omg_func_table.get(name);
    if (!fn) omg_panic('UndefinedIdentError', name);
    return fn;
}

// Default-injected globals. Programs may shadow these.
// `args` and friends are `let` so the page can override them before
// re-eval-ing the playground bundle on each Run click. The `v_*`
// aliases match what native-js.omg's `js_var()` emits for source-
// level references (LOAD "args" → `v_args`).
let args = (typeof process !== 'undefined') ? process.argv.slice(1) : [];
let module_file = '';
let current_dir = (typeof process !== 'undefined') ? process.cwd() : '/';
let v_args = args;
let v_module_file = module_file;
let v_current_dir = current_dir;

// === Program ==============================================================

let v_maze;
let v_start;
let v_goal;
let v_key;
let v_contains;
let v_set_prev;
let v_get_prev;
let v_neighbors;
let v_bfs;
let v_path;

function omg_p0(_captured, v_start, v_goal) {
    let v_queue;
    let v_visited;
    let v_prev;
    let v_current;
    let v_path;
    let v_k;
    let v_p;
    let v_neigh;
    let v_i;
    let v_n;
    const _s = [];
    let _ip = 279;
    let _eh = [];
    while (true) {
        try {
            switch (_ip) {
            case 279: {
    _s.push(v_start);
            }
            // fall through to 280
            case 280: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
            }
            // fall through to 281
            case 281: {
    v_queue = _s.pop();
            }
            // fall through to 282
            case 282: {
    _s.push(v_start);
            }
            // fall through to 283
            case 283: {
    { const _argv = _s.splice(_s.length - 1, 1); _s.push(omg_p3(null, ..._argv)); }
            }
            // fall through to 284
            case 284: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
            }
            // fall through to 285
            case 285: {
    v_visited = _s.pop();
            }
            // fall through to 286
            case 286: {
    { const _arr = _s.splice(_s.length - 0, 0); _s.push(_arr); }
            }
            // fall through to 287
            case 287: {
    v_prev = _s.pop();
            }
            // fall through to 288
            case 288: {
    { const _arr = _s.splice(_s.length - 0, 0); _s.push(_arr); }
            }
            // fall through to 289
            case 289: {
    v_current = _s.pop();
            }
            // fall through to 290
            case 290: {
    _s.push(v_queue);
            }
            // fall through to 291
            case 291: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
            }
            // fall through to 292
            case 292: {
    _s.push(0n);
            }
            // fall through to 293
            case 293: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_gt(_a, _b)); }
            }
            // fall through to 294
            case 294: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 401; continue; } }
            }
            // fall through to 295
            case 295: {
    _s.push(v_queue);
            }
            // fall through to 296
            case 296: {
    _s.push(0n);
            }
            // fall through to 297
            case 297: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 298
            case 298: {
    v_current = _s.pop();
            }
            // fall through to 299
            case 299: {
    _s.push(v_queue);
            }
            // fall through to 300
            case 300: {
    _s.push(1n);
            }
            // fall through to 301
            case 301: {
    _s.push(v_queue);
            }
            // fall through to 302
            case 302: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
            }
            // fall through to 303
            case 303: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
            }
            // fall through to 304
            case 304: {
    v_queue = _s.pop();
            }
            // fall through to 305
            case 305: {
    _s.push(v_current);
            }
            // fall through to 306
            case 306: {
    _s.push(0n);
            }
            // fall through to 307
            case 307: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 308
            case 308: {
    _s.push(v_goal);
            }
            // fall through to 309
            case 309: {
    _s.push(0n);
            }
            // fall through to 310
            case 310: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 311
            case 311: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
            }
            // fall through to 312
            case 312: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 323; continue; } }
            }
            // fall through to 313
            case 313: {
    _s.push(v_current);
            }
            // fall through to 314
            case 314: {
    _s.push(1n);
            }
            // fall through to 315
            case 315: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 316
            case 316: {
    _s.push(v_goal);
            }
            // fall through to 317
            case 317: {
    _s.push(1n);
            }
            // fall through to 318
            case 318: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 319
            case 319: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
            }
            // fall through to 320
            case 320: {
    _s.push(true);
            }
            // fall through to 321
            case 321: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_truthy(_a) && omg_truthy(_b)); }
            }
            // fall through to 322
            case 322: {
    _ip = 324; continue;
            }
            // fall through to 323
            case 323: {
    _s.push(false);
            }
            // fall through to 324
            case 324: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 356; continue; } }
            }
            // fall through to 325
            case 325: {
    _s.push(v_current);
            }
            // fall through to 326
            case 326: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
            }
            // fall through to 327
            case 327: {
    v_path = _s.pop();
            }
            // fall through to 328
            case 328: {
    _s.push(v_current);
            }
            // fall through to 329
            case 329: {
    { const _argv = _s.splice(_s.length - 1, 1); _s.push(omg_p3(null, ..._argv)); }
            }
            // fall through to 330
            case 330: {
    v_k = _s.pop();
            }
            // fall through to 331
            case 331: {
    _s.push(v_prev);
            }
            // fall through to 332
            case 332: {
    _s.push(v_k);
            }
            // fall through to 333
            case 333: {
    { const _argv = _s.splice(_s.length - 2, 2); _s.push(omg_p2(null, ..._argv)); }
            }
            // fall through to 334
            case 334: {
    v_p = _s.pop();
            }
            // fall through to 335
            case 335: {
    _s.push(v_p);
            }
            // fall through to 336
            case 336: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
            }
            // fall through to 337
            case 337: {
    _s.push(0n);
            }
            // fall through to 338
            case 338: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_gt(_a, _b)); }
            }
            // fall through to 339
            case 339: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 353; continue; } }
            }
            // fall through to 340
            case 340: {
    _s.push(v_p);
            }
            // fall through to 341
            case 341: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
            }
            // fall through to 342
            case 342: {
    _s.push(v_path);
            }
            // fall through to 343
            case 343: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 344
            case 344: {
    v_path = _s.pop();
            }
            // fall through to 345
            case 345: {
    _s.push(v_p);
            }
            // fall through to 346
            case 346: {
    { const _argv = _s.splice(_s.length - 1, 1); _s.push(omg_p3(null, ..._argv)); }
            }
            // fall through to 347
            case 347: {
    v_k = _s.pop();
            }
            // fall through to 348
            case 348: {
    _s.push(v_prev);
            }
            // fall through to 349
            case 349: {
    _s.push(v_k);
            }
            // fall through to 350
            case 350: {
    { const _argv = _s.splice(_s.length - 2, 2); _s.push(omg_p2(null, ..._argv)); }
            }
            // fall through to 351
            case 351: {
    v_p = _s.pop();
            }
            // fall through to 352
            case 352: {
    _ip = 335; continue;
            }
            // fall through to 353
            case 353: {
    _s.push(v_path);
            }
            // fall through to 354
            case 354: {
    return _s.pop();
            }
            // fall through to 355
            case 355: {
    _ip = 356; continue;
            }
            // fall through to 356
            case 356: {
    _s.push(v_current);
            }
            // fall through to 357
            case 357: {
    { const _argv = _s.splice(_s.length - 1, 1); _s.push(omg_p4(null, ..._argv)); }
            }
            // fall through to 358
            case 358: {
    v_neigh = _s.pop();
            }
            // fall through to 359
            case 359: {
    _s.push(0n);
            }
            // fall through to 360
            case 360: {
    v_i = _s.pop();
            }
            // fall through to 361
            case 361: {
    _s.push(v_i);
            }
            // fall through to 362
            case 362: {
    _s.push(v_neigh);
            }
            // fall through to 363
            case 363: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
            }
            // fall through to 364
            case 364: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
            }
            // fall through to 365
            case 365: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 400; continue; } }
            }
            // fall through to 366
            case 366: {
    _s.push(v_neigh);
            }
            // fall through to 367
            case 367: {
    _s.push(v_i);
            }
            // fall through to 368
            case 368: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 369
            case 369: {
    v_n = _s.pop();
            }
            // fall through to 370
            case 370: {
    _s.push(v_n);
            }
            // fall through to 371
            case 371: {
    { const _argv = _s.splice(_s.length - 1, 1); _s.push(omg_p3(null, ..._argv)); }
            }
            // fall through to 372
            case 372: {
    v_k = _s.pop();
            }
            // fall through to 373
            case 373: {
    _s.push(v_visited);
            }
            // fall through to 374
            case 374: {
    _s.push(v_k);
            }
            // fall through to 375
            case 375: {
    { const _argv = _s.splice(_s.length - 2, 2); _s.push(omg_p1(null, ..._argv)); }
            }
            // fall through to 376
            case 376: {
    _s.push(false);
            }
            // fall through to 377
            case 377: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
            }
            // fall through to 378
            case 378: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 395; continue; } }
            }
            // fall through to 379
            case 379: {
    _s.push(v_visited);
            }
            // fall through to 380
            case 380: {
    _s.push(v_k);
            }
            // fall through to 381
            case 381: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
            }
            // fall through to 382
            case 382: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 383
            case 383: {
    v_visited = _s.pop();
            }
            // fall through to 384
            case 384: {
    _s.push(v_prev);
            }
            // fall through to 385
            case 385: {
    _s.push(v_k);
            }
            // fall through to 386
            case 386: {
    _s.push(v_current);
            }
            // fall through to 387
            case 387: {
    { const _argv = _s.splice(_s.length - 3, 3); _s.push(omg_p5(null, ..._argv)); }
            }
            // fall through to 388
            case 388: {
    v_prev = _s.pop();
            }
            // fall through to 389
            case 389: {
    _s.push(v_queue);
            }
            // fall through to 390
            case 390: {
    _s.push(v_n);
            }
            // fall through to 391
            case 391: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
            }
            // fall through to 392
            case 392: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 393
            case 393: {
    v_queue = _s.pop();
            }
            // fall through to 394
            case 394: {
    _ip = 395; continue;
            }
            // fall through to 395
            case 395: {
    _s.push(v_i);
            }
            // fall through to 396
            case 396: {
    _s.push(1n);
            }
            // fall through to 397
            case 397: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 398
            case 398: {
    v_i = _s.pop();
            }
            // fall through to 399
            case 399: {
    _ip = 361; continue;
            }
            // fall through to 400
            case 400: {
    _ip = 290; continue;
            }
            // fall through to 401
            case 401: {
    { const _arr = _s.splice(_s.length - 0, 0); _s.push(_arr); }
            }
            // fall through to 402
            case 402: {
    return _s.pop();
            }
            // fall through to 403
            case 403: {
    _s.push(null);
            }
            // fall through to 404
            case 404: {
    return _s.pop();
            }
            // fall through to 405
            default: return;
            }
            _ip += 1;
        } catch (_e) {
            if (_e instanceof OmgError && _eh.length > 0) {
                _ip = _eh.pop();
                _s.length = 0;
                _s.push(_e.kind + ': ' + _e.omgMessage);
            } else { throw _e; }
        }
    }
}

function omg_p1(_captured, v_xs, v_x) {
    let v_i;
    const _s = [];
    let _ip = 65;
    let _eh = [];
    while (true) {
        try {
            switch (_ip) {
            case 65: {
    _s.push(0n);
            }
            // fall through to 66
            case 66: {
    v_i = _s.pop();
            }
            // fall through to 67
            case 67: {
    _s.push(v_i);
            }
            // fall through to 68
            case 68: {
    _s.push(v_xs);
            }
            // fall through to 69
            case 69: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
            }
            // fall through to 70
            case 70: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
            }
            // fall through to 71
            case 71: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 86; continue; } }
            }
            // fall through to 72
            case 72: {
    _s.push(v_xs);
            }
            // fall through to 73
            case 73: {
    _s.push(v_i);
            }
            // fall through to 74
            case 74: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 75
            case 75: {
    _s.push(v_x);
            }
            // fall through to 76
            case 76: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
            }
            // fall through to 77
            case 77: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 81; continue; } }
            }
            // fall through to 78
            case 78: {
    _s.push(true);
            }
            // fall through to 79
            case 79: {
    return _s.pop();
            }
            // fall through to 80
            case 80: {
    _ip = 81; continue;
            }
            // fall through to 81
            case 81: {
    _s.push(v_i);
            }
            // fall through to 82
            case 82: {
    _s.push(1n);
            }
            // fall through to 83
            case 83: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 84
            case 84: {
    v_i = _s.pop();
            }
            // fall through to 85
            case 85: {
    _ip = 67; continue;
            }
            // fall through to 86
            case 86: {
    _s.push(false);
            }
            // fall through to 87
            case 87: {
    return _s.pop();
            }
            // fall through to 88
            case 88: {
    _s.push(null);
            }
            // fall through to 89
            case 89: {
    return _s.pop();
            }
            // fall through to 90
            default: return;
            }
            _ip += 1;
        } catch (_e) {
            if (_e instanceof OmgError && _eh.length > 0) {
                _ip = _eh.pop();
                _s.length = 0;
                _s.push(_e.kind + ': ' + _e.omgMessage);
            } else { throw _e; }
        }
    }
}

function omg_p2(_captured, v_prev, v_k) {
    let v_i;
    const _s = [];
    let _ip = 142;
    let _eh = [];
    while (true) {
        try {
            switch (_ip) {
            case 142: {
    _s.push(0n);
            }
            // fall through to 143
            case 143: {
    v_i = _s.pop();
            }
            // fall through to 144
            case 144: {
    _s.push(v_i);
            }
            // fall through to 145
            case 145: {
    _s.push(v_prev);
            }
            // fall through to 146
            case 146: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
            }
            // fall through to 147
            case 147: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
            }
            // fall through to 148
            case 148: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 169; continue; } }
            }
            // fall through to 149
            case 149: {
    _s.push(v_prev);
            }
            // fall through to 150
            case 150: {
    _s.push(v_i);
            }
            // fall through to 151
            case 151: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 152
            case 152: {
    _s.push(0n);
            }
            // fall through to 153
            case 153: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 154
            case 154: {
    _s.push(v_k);
            }
            // fall through to 155
            case 155: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
            }
            // fall through to 156
            case 156: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 164; continue; } }
            }
            // fall through to 157
            case 157: {
    _s.push(v_prev);
            }
            // fall through to 158
            case 158: {
    _s.push(v_i);
            }
            // fall through to 159
            case 159: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 160
            case 160: {
    _s.push(1n);
            }
            // fall through to 161
            case 161: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 162
            case 162: {
    return _s.pop();
            }
            // fall through to 163
            case 163: {
    _ip = 164; continue;
            }
            // fall through to 164
            case 164: {
    _s.push(v_i);
            }
            // fall through to 165
            case 165: {
    _s.push(1n);
            }
            // fall through to 166
            case 166: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 167
            case 167: {
    v_i = _s.pop();
            }
            // fall through to 168
            case 168: {
    _ip = 144; continue;
            }
            // fall through to 169
            case 169: {
    { const _arr = _s.splice(_s.length - 0, 0); _s.push(_arr); }
            }
            // fall through to 170
            case 170: {
    return _s.pop();
            }
            // fall through to 171
            case 171: {
    _s.push(null);
            }
            // fall through to 172
            case 172: {
    return _s.pop();
            }
            // fall through to 173
            default: return;
            }
            _ip += 1;
        } catch (_e) {
            if (_e instanceof OmgError && _eh.length > 0) {
                _ip = _eh.pop();
                _s.length = 0;
                _s.push(_e.kind + ': ' + _e.omgMessage);
            } else { throw _e; }
        }
    }
}

function omg_p3(_captured, v_p) {
    const _s = [];
    let _ip = 53;
    let _eh = [];
    while (true) {
        try {
            switch (_ip) {
            case 53: {
    _s.push(v_p);
            }
            // fall through to 54
            case 54: {
    _s.push(0n);
            }
            // fall through to 55
            case 55: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 56
            case 56: {
    _s.push(",");
            }
            // fall through to 57
            case 57: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 58
            case 58: {
    _s.push(v_p);
            }
            // fall through to 59
            case 59: {
    _s.push(1n);
            }
            // fall through to 60
            case 60: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 61
            case 61: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 62
            case 62: {
    return _s.pop();
            }
            // fall through to 63
            case 63: {
    _s.push(null);
            }
            // fall through to 64
            case 64: {
    return _s.pop();
            }
            // fall through to 65
            default: return;
            }
            _ip += 1;
        } catch (_e) {
            if (_e instanceof OmgError && _eh.length > 0) {
                _ip = _eh.pop();
                _s.length = 0;
                _s.push(_e.kind + ': ' + _e.omgMessage);
            } else { throw _e; }
        }
    }
}

function omg_p4(_captured, v_p) {
    let v_dirs;
    let v_result;
    let v_i;
    let v_nx;
    let v_ny;
    const _s = [];
    let _ip = 173;
    let _eh = [];
    while (true) {
        try {
            switch (_ip) {
            case 173: {
    _s.push(1n);
            }
            // fall through to 174
            case 174: {
    _s.push(0n);
            }
            // fall through to 175
            case 175: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
            }
            // fall through to 176
            case 176: {
    _s.push(1n);
            }
            // fall through to 177
            case 177: {
    { const _a = _s.pop(); _s.push(omg_neg(_a)); }
            }
            // fall through to 178
            case 178: {
    _s.push(0n);
            }
            // fall through to 179
            case 179: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
            }
            // fall through to 180
            case 180: {
    _s.push(0n);
            }
            // fall through to 181
            case 181: {
    _s.push(1n);
            }
            // fall through to 182
            case 182: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
            }
            // fall through to 183
            case 183: {
    _s.push(0n);
            }
            // fall through to 184
            case 184: {
    _s.push(1n);
            }
            // fall through to 185
            case 185: {
    { const _a = _s.pop(); _s.push(omg_neg(_a)); }
            }
            // fall through to 186
            case 186: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
            }
            // fall through to 187
            case 187: {
    { const _arr = _s.splice(_s.length - 4, 4); _s.push(_arr); }
            }
            // fall through to 188
            case 188: {
    v_dirs = _s.pop();
            }
            // fall through to 189
            case 189: {
    { const _arr = _s.splice(_s.length - 0, 0); _s.push(_arr); }
            }
            // fall through to 190
            case 190: {
    v_result = _s.pop();
            }
            // fall through to 191
            case 191: {
    _s.push(0n);
            }
            // fall through to 192
            case 192: {
    v_i = _s.pop();
            }
            // fall through to 193
            case 193: {
    _s.push(v_i);
            }
            // fall through to 194
            case 194: {
    _s.push(v_dirs);
            }
            // fall through to 195
            case 195: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
            }
            // fall through to 196
            case 196: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
            }
            // fall through to 197
            case 197: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 275; continue; } }
            }
            // fall through to 198
            case 198: {
    _s.push(v_p);
            }
            // fall through to 199
            case 199: {
    _s.push(0n);
            }
            // fall through to 200
            case 200: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 201
            case 201: {
    _s.push(v_dirs);
            }
            // fall through to 202
            case 202: {
    _s.push(v_i);
            }
            // fall through to 203
            case 203: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 204
            case 204: {
    _s.push(0n);
            }
            // fall through to 205
            case 205: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 206
            case 206: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 207
            case 207: {
    v_nx = _s.pop();
            }
            // fall through to 208
            case 208: {
    _s.push(v_p);
            }
            // fall through to 209
            case 209: {
    _s.push(1n);
            }
            // fall through to 210
            case 210: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 211
            case 211: {
    _s.push(v_dirs);
            }
            // fall through to 212
            case 212: {
    _s.push(v_i);
            }
            // fall through to 213
            case 213: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 214
            case 214: {
    _s.push(1n);
            }
            // fall through to 215
            case 215: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 216
            case 216: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 217
            case 217: {
    v_ny = _s.pop();
            }
            // fall through to 218
            case 218: {
    _s.push(v_nx);
            }
            // fall through to 219
            case 219: {
    _s.push(0n);
            }
            // fall through to 220
            case 220: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_ge(_a, _b)); }
            }
            // fall through to 221
            case 221: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 229; continue; } }
            }
            // fall through to 222
            case 222: {
    _s.push(v_nx);
            }
            // fall through to 223
            case 223: {
    _s.push(v_maze);
            }
            // fall through to 224
            case 224: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
            }
            // fall through to 225
            case 225: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
            }
            // fall through to 226
            case 226: {
    _s.push(true);
            }
            // fall through to 227
            case 227: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_truthy(_a) && omg_truthy(_b)); }
            }
            // fall through to 228
            case 228: {
    _ip = 230; continue;
            }
            // fall through to 229
            case 229: {
    _s.push(false);
            }
            // fall through to 230
            case 230: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 237; continue; } }
            }
            // fall through to 231
            case 231: {
    _s.push(v_ny);
            }
            // fall through to 232
            case 232: {
    _s.push(0n);
            }
            // fall through to 233
            case 233: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_ge(_a, _b)); }
            }
            // fall through to 234
            case 234: {
    _s.push(true);
            }
            // fall through to 235
            case 235: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_truthy(_a) && omg_truthy(_b)); }
            }
            // fall through to 236
            case 236: {
    _ip = 238; continue;
            }
            // fall through to 237
            case 237: {
    _s.push(false);
            }
            // fall through to 238
            case 238: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 248; continue; } }
            }
            // fall through to 239
            case 239: {
    _s.push(v_ny);
            }
            // fall through to 240
            case 240: {
    _s.push(v_maze);
            }
            // fall through to 241
            case 241: {
    _s.push(0n);
            }
            // fall through to 242
            case 242: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 243
            case 243: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
            }
            // fall through to 244
            case 244: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
            }
            // fall through to 245
            case 245: {
    _s.push(true);
            }
            // fall through to 246
            case 246: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_truthy(_a) && omg_truthy(_b)); }
            }
            // fall through to 247
            case 247: {
    _ip = 249; continue;
            }
            // fall through to 248
            case 248: {
    _s.push(false);
            }
            // fall through to 249
            case 249: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 260; continue; } }
            }
            // fall through to 250
            case 250: {
    _s.push(v_maze);
            }
            // fall through to 251
            case 251: {
    _s.push(v_nx);
            }
            // fall through to 252
            case 252: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 253
            case 253: {
    _s.push(v_ny);
            }
            // fall through to 254
            case 254: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 255
            case 255: {
    _s.push(0n);
            }
            // fall through to 256
            case 256: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
            }
            // fall through to 257
            case 257: {
    _s.push(true);
            }
            // fall through to 258
            case 258: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_truthy(_a) && omg_truthy(_b)); }
            }
            // fall through to 259
            case 259: {
    _ip = 261; continue;
            }
            // fall through to 260
            case 260: {
    _s.push(false);
            }
            // fall through to 261
            case 261: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 270; continue; } }
            }
            // fall through to 262
            case 262: {
    _s.push(v_result);
            }
            // fall through to 263
            case 263: {
    _s.push(v_nx);
            }
            // fall through to 264
            case 264: {
    _s.push(v_ny);
            }
            // fall through to 265
            case 265: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
            }
            // fall through to 266
            case 266: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
            }
            // fall through to 267
            case 267: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 268
            case 268: {
    v_result = _s.pop();
            }
            // fall through to 269
            case 269: {
    _ip = 270; continue;
            }
            // fall through to 270
            case 270: {
    _s.push(v_i);
            }
            // fall through to 271
            case 271: {
    _s.push(1n);
            }
            // fall through to 272
            case 272: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 273
            case 273: {
    v_i = _s.pop();
            }
            // fall through to 274
            case 274: {
    _ip = 193; continue;
            }
            // fall through to 275
            case 275: {
    _s.push(v_result);
            }
            // fall through to 276
            case 276: {
    return _s.pop();
            }
            // fall through to 277
            case 277: {
    _s.push(null);
            }
            // fall through to 278
            case 278: {
    return _s.pop();
            }
            // fall through to 279
            default: return;
            }
            _ip += 1;
        } catch (_e) {
            if (_e instanceof OmgError && _eh.length > 0) {
                _ip = _eh.pop();
                _s.length = 0;
                _s.push(_e.kind + ': ' + _e.omgMessage);
            } else { throw _e; }
        }
    }
}

function omg_p5(_captured, v_prev, v_k, v_v) {
    let v_i;
    const _s = [];
    let _ip = 90;
    let _eh = [];
    while (true) {
        try {
            switch (_ip) {
            case 90: {
    _s.push(0n);
            }
            // fall through to 91
            case 91: {
    v_i = _s.pop();
            }
            // fall through to 92
            case 92: {
    _s.push(v_i);
            }
            // fall through to 93
            case 93: {
    _s.push(v_prev);
            }
            // fall through to 94
            case 94: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
            }
            // fall through to 95
            case 95: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
            }
            // fall through to 96
            case 96: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 131; continue; } }
            }
            // fall through to 97
            case 97: {
    _s.push(v_prev);
            }
            // fall through to 98
            case 98: {
    _s.push(v_i);
            }
            // fall through to 99
            case 99: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 100
            case 100: {
    _s.push(0n);
            }
            // fall through to 101
            case 101: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 102
            case 102: {
    _s.push(v_k);
            }
            // fall through to 103
            case 103: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
            }
            // fall through to 104
            case 104: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 126; continue; } }
            }
            // fall through to 105
            case 105: {
    _s.push(v_prev);
            }
            // fall through to 106
            case 106: {
    _s.push(0n);
            }
            // fall through to 107
            case 107: {
    _s.push(v_i);
            }
            // fall through to 108
            case 108: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
            }
            // fall through to 109
            case 109: {
    _s.push(v_k);
            }
            // fall through to 110
            case 110: {
    _s.push(v_v);
            }
            // fall through to 111
            case 111: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
            }
            // fall through to 112
            case 112: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
            }
            // fall through to 113
            case 113: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 114
            case 114: {
    _s.push(v_prev);
            }
            // fall through to 115
            case 115: {
    _s.push(v_i);
            }
            // fall through to 116
            case 116: {
    _s.push(1n);
            }
            // fall through to 117
            case 117: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 118
            case 118: {
    _s.push(v_prev);
            }
            // fall through to 119
            case 119: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
            }
            // fall through to 120
            case 120: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
            }
            // fall through to 121
            case 121: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 122
            case 122: {
    v_prev = _s.pop();
            }
            // fall through to 123
            case 123: {
    _s.push(v_prev);
            }
            // fall through to 124
            case 124: {
    return _s.pop();
            }
            // fall through to 125
            case 125: {
    _ip = 126; continue;
            }
            // fall through to 126
            case 126: {
    _s.push(v_i);
            }
            // fall through to 127
            case 127: {
    _s.push(1n);
            }
            // fall through to 128
            case 128: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 129
            case 129: {
    v_i = _s.pop();
            }
            // fall through to 130
            case 130: {
    _ip = 92; continue;
            }
            // fall through to 131
            case 131: {
    _s.push(v_prev);
            }
            // fall through to 132
            case 132: {
    _s.push(v_k);
            }
            // fall through to 133
            case 133: {
    _s.push(v_v);
            }
            // fall through to 134
            case 134: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
            }
            // fall through to 135
            case 135: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
            }
            // fall through to 136
            case 136: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 137
            case 137: {
    v_prev = _s.pop();
            }
            // fall through to 138
            case 138: {
    _s.push(v_prev);
            }
            // fall through to 139
            case 139: {
    return _s.pop();
            }
            // fall through to 140
            case 140: {
    _s.push(null);
            }
            // fall through to 141
            case 141: {
    return _s.pop();
            }
            // fall through to 142
            default: return;
            }
            _ip += 1;
        } catch (_e) {
            if (_e instanceof OmgError && _eh.length > 0) {
                _ip = _eh.pop();
                _s.length = 0;
                _s.push(_e.kind + ': ' + _e.omgMessage);
            } else { throw _e; }
        }
    }
}

omg_func_table.set("bfs", omg_p0);
omg_func_table.set("contains", omg_p1);
omg_func_table.set("get_prev", omg_p2);
omg_func_table.set("key", omg_p3);
omg_func_table.set("neighbors", omg_p4);
omg_func_table.set("set_prev", omg_p5);

try {
(function _omg_main() {
    const _s = [];
    let _ip = 0;
    let _eh = [];
    while (true) {
        try {
            switch (_ip) {
            case 0: {
    _s.push(0n);
            }
            // fall through to 1
            case 1: {
    _s.push(0n);
            }
            // fall through to 2
            case 2: {
    _s.push(0n);
            }
            // fall through to 3
            case 3: {
    _s.push(0n);
            }
            // fall through to 4
            case 4: {
    _s.push(0n);
            }
            // fall through to 5
            case 5: {
    { const _arr = _s.splice(_s.length - 5, 5); _s.push(_arr); }
            }
            // fall through to 6
            case 6: {
    _s.push(1n);
            }
            // fall through to 7
            case 7: {
    _s.push(1n);
            }
            // fall through to 8
            case 8: {
    _s.push(0n);
            }
            // fall through to 9
            case 9: {
    _s.push(1n);
            }
            // fall through to 10
            case 10: {
    _s.push(0n);
            }
            // fall through to 11
            case 11: {
    { const _arr = _s.splice(_s.length - 5, 5); _s.push(_arr); }
            }
            // fall through to 12
            case 12: {
    _s.push(0n);
            }
            // fall through to 13
            case 13: {
    _s.push(0n);
            }
            // fall through to 14
            case 14: {
    _s.push(0n);
            }
            // fall through to 15
            case 15: {
    _s.push(1n);
            }
            // fall through to 16
            case 16: {
    _s.push(0n);
            }
            // fall through to 17
            case 17: {
    { const _arr = _s.splice(_s.length - 5, 5); _s.push(_arr); }
            }
            // fall through to 18
            case 18: {
    _s.push(0n);
            }
            // fall through to 19
            case 19: {
    _s.push(1n);
            }
            // fall through to 20
            case 20: {
    _s.push(1n);
            }
            // fall through to 21
            case 21: {
    _s.push(1n);
            }
            // fall through to 22
            case 22: {
    _s.push(0n);
            }
            // fall through to 23
            case 23: {
    { const _arr = _s.splice(_s.length - 5, 5); _s.push(_arr); }
            }
            // fall through to 24
            case 24: {
    _s.push(0n);
            }
            // fall through to 25
            case 25: {
    _s.push(0n);
            }
            // fall through to 26
            case 26: {
    _s.push(0n);
            }
            // fall through to 27
            case 27: {
    _s.push(0n);
            }
            // fall through to 28
            case 28: {
    _s.push(0n);
            }
            // fall through to 29
            case 29: {
    { const _arr = _s.splice(_s.length - 5, 5); _s.push(_arr); }
            }
            // fall through to 30
            case 30: {
    { const _arr = _s.splice(_s.length - 5, 5); _s.push(_arr); }
            }
            // fall through to 31
            case 31: {
    v_maze = _s.pop();
            }
            // fall through to 32
            case 32: {
    _s.push(0n);
            }
            // fall through to 33
            case 33: {
    _s.push(0n);
            }
            // fall through to 34
            case 34: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
            }
            // fall through to 35
            case 35: {
    v_start = _s.pop();
            }
            // fall through to 36
            case 36: {
    _s.push(4n);
            }
            // fall through to 37
            case 37: {
    _s.push(4n);
            }
            // fall through to 38
            case 38: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
            }
            // fall through to 39
            case 39: {
    v_goal = _s.pop();
            }
            // fall through to 40
            case 40: {
    {
        const _cap = new Map();
        v_key = (...args) => omg_p3(_cap, ...args);
    }
            }
            // fall through to 41
            case 41: {
    {
        const _cap = new Map();
        v_contains = (...args) => omg_p1(_cap, ...args);
    }
            }
            // fall through to 42
            case 42: {
    {
        const _cap = new Map();
        v_set_prev = (...args) => omg_p5(_cap, ...args);
    }
            }
            // fall through to 43
            case 43: {
    {
        const _cap = new Map();
        v_get_prev = (...args) => omg_p2(_cap, ...args);
    }
            }
            // fall through to 44
            case 44: {
    {
        const _cap = new Map();
        v_neighbors = (...args) => omg_p4(_cap, ...args);
    }
            }
            // fall through to 45
            case 45: {
    {
        const _cap = new Map();
        v_bfs = (...args) => omg_p0(_cap, ...args);
    }
            }
            // fall through to 46
            case 46: {
    _s.push(v_start);
            }
            // fall through to 47
            case 47: {
    _s.push(v_goal);
            }
            // fall through to 48
            case 48: {
    { const _argv = _s.splice(_s.length - 2, 2); _s.push(omg_p0(null, ..._argv)); }
            }
            // fall through to 49
            case 49: {
    v_path = _s.pop();
            }
            // fall through to 50
            case 50: {
    _s.push(v_path);
            }
            // fall through to 51
            case 51: {
    omg_emit(_s.pop());
            }
            // fall through to 52
            case 52: {
    return;
            }
            // fall through to 53
            default: return;
            }
            _ip += 1;
        } catch (_e) {
            if (_e instanceof OmgError && _eh.length > 0) {
                _ip = _eh.pop();
                _s.length = 0;
                _s.push(_e.kind + ': ' + _e.omgMessage);
            } else { throw _e; }
        }
    }
})();
} catch (_e) {
    if (_e instanceof OmgError) {
        if (typeof process !== 'undefined') { process.stderr.write(_e.kind + ': ' + _e.omgMessage + '\n'); process.exit(1); }
        else throw _e;
    } else { throw _e; }
}
