// Generated by bootstrap/src/native-js.omg from /tmp/tmp.hCDlUjspXy/stack_vm.omgb
// Do not edit by hand.

// omg_rt.js — runtime for OMG programs compiled to JavaScript.
//
// Mirrors bootstrap/src/omg_rt.h: provides the value coercion, the
// arithmetic/string ops, and the builtins that AOT-emitted JS calls
// into. Every program transpiled by bootstrap/src/native-js.omg
// inlines this file at the top of its .js output, so the result is
// a single self-contained JS file you can hand to `node` or run in a
// browser.
//
// Value representation:
//   ints    → JS BigInt  (so OMG's i64 semantics survive bitwise ops
//                         past 2^53; arithmetic stays exact)
//   floats  → JS Number  (OMG floats are IEEE-754 f64; same as JS)
//   strings → JS string
//   bools   → JS boolean
//   lists   → JS Array
//   dicts   → JS Map     (preserves insertion order, string keys)
//   none    → null
//   closure → JS function with .__omg_captured marker
//
// We tag the few cases JS can't distinguish on its own (Number vs
// BigInt is the only one that needs care; everything else falls out
// of `typeof`). Most ops accept either int (BigInt) or float
// (Number) and dispatch off `typeof`.

'use strict';

// === Type discrimination ===================================================

function omg_is_int(v)    { return typeof v === 'bigint'; }
function omg_is_float(v)  { return typeof v === 'number'; }
function omg_is_str(v)    { return typeof v === 'string'; }
function omg_is_bool(v)   { return typeof v === 'boolean'; }
function omg_is_list(v)   { return Array.isArray(v); }
function omg_is_dict(v)   { return v instanceof Map; }
function omg_is_none(v)   { return v === null; }
function omg_is_closure(v){ return typeof v === 'function' && v.__omg_captured !== undefined; }

// === Coercion (mirror of omg_as_int / omg_as_double in omg_rt.h) ==========

function omg_as_int(v) {
    if (typeof v === 'bigint') return v;
    if (typeof v === 'boolean') return v ? 1n : 0n;
    if (typeof v === 'number') {
        if (!Number.isFinite(v)) {
            throw new OmgError('ValueError',
                'cannot convert non-finite float to int: ' + v);
        }
        if (v < -9223372036854775808 || v > 9223372036854775807) {
            throw new OmgError('ValueError',
                'float ' + v + ' is outside the i64 range');
        }
        return BigInt(Math.trunc(v));
    }
    if (typeof v === 'string') {
        // Match Rust's Value::as_int and omg_rt.h's omg_as_int:
        // strict integer parse, no whitespace, no junk tail.
        if (!/^-?\d+$/.test(v)) {
            throw new OmgError('TypeError',
                "Invalid literal for int(): '" + v + "'");
        }
        return BigInt(v);
    }
    if (Array.isArray(v)) {
        throw new OmgError('TypeError',
            'cannot convert list to int (use length() instead)');
    }
    if (v instanceof Map) {
        throw new OmgError('TypeError', 'cannot convert dict to int');
    }
    if (v === null) {
        throw new OmgError('TypeError', 'cannot convert none to int');
    }
    if (typeof v === 'function') {
        throw new OmgError('TypeError', 'cannot convert function to int');
    }
    throw new OmgError('TypeError', 'cannot convert value to int');
}

function omg_as_float(v) {
    if (typeof v === 'number') return v;
    if (typeof v === 'bigint') return Number(v);
    if (typeof v === 'boolean') return v ? 1 : 0;
    if (typeof v === 'string') {
        const trimmed = v;
        if (!/^-?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?$/.test(trimmed)) {
            throw new OmgError('TypeError',
                "Invalid literal for float(): '" + v + "'");
        }
        return parseFloat(trimmed);
    }
    if (Array.isArray(v)) {
        throw new OmgError('TypeError', 'cannot convert list to float');
    }
    throw new OmgError('TypeError', 'cannot convert value to float');
}

function omg_truthy(v) {
    if (v === null) return false;
    if (typeof v === 'boolean') return v;
    if (typeof v === 'bigint') return v !== 0n;
    if (typeof v === 'number') return v !== 0;
    if (typeof v === 'string') return v.length > 0;
    if (Array.isArray(v)) return v.length > 0;
    if (v instanceof Map) return v.size > 0;
    return true;
}

// === Errors ================================================================

class OmgError extends Error {
    constructor(kind, message) {
        super(kind + ': ' + message);
        this.kind = kind;
        this.omgMessage = message;
    }
}

function omg_panic(kind, msg) { throw new OmgError(kind, msg); }

// === to_string + emit ======================================================

// Mirrors omg_rt.h's omg_value_to_cstr / omg_print_value. Used by
// `emit` and by string concatenation when one side is non-string.
function omg_to_string(v) {
    if (v === null) return '';
    if (typeof v === 'boolean') return v ? 'true' : 'false';
    if (typeof v === 'string') return v;
    if (typeof v === 'bigint') return v.toString();
    if (typeof v === 'number') {
        // Match OMG's float printing: integer-valued floats print
        // with a trailing ".0", scientific for very small/large.
        if (Number.isFinite(v) && Number.isInteger(v) && Math.abs(v) < 1e16) {
            return v.toFixed(1);
        }
        return v.toString();
    }
    if (Array.isArray(v)) {
        return '[' + v.map(omg_to_string).join(', ') + ']';
    }
    if (v instanceof Map) {
        const parts = [];
        for (const [k, val] of v) parts.push(k + ': ' + omg_to_string(val));
        return '{' + parts.join(', ') + '}';
    }
    if (typeof v === 'function') return '<proc>';
    return String(v);
}

// emit: print to stdout with a trailing newline. In node we use
// console.log which adds the newline; for browser playgrounds we
// override _omg_write to redirect into the page.
let _omg_write = (s) => { console.log(s); };
function omg_emit(v) { _omg_write(omg_to_string(v)); }

// print: same channel, no trailing newline. Used by REPL prompts.
let _omg_print_raw = (s) => { process.stdout.write(s); };
function omg_print(v) {
    if (typeof v !== 'string') {
        omg_panic('TypeError', 'print() expects a string');
    }
    _omg_print_raw(v);
}

// === Stack helper for compound emit ========================================
// (Used by the generated code to manage operand stacks; no-op here
// since we just give programs direct access to a JS array.)

// === Arithmetic ============================================================

function omg_add(a, b) {
    if (typeof a === 'string' || typeof b === 'string') {
        return omg_to_string(a) + omg_to_string(b);
    }
    if (Array.isArray(a) && Array.isArray(b)) {
        return a.concat(b);
    }
    if (typeof a === 'number' || typeof b === 'number') {
        return omg_as_float(a) + omg_as_float(b);
    }
    return omg_as_int(a) + omg_as_int(b);
}

function omg_sub(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        return omg_as_float(a) - omg_as_float(b);
    }
    return omg_as_int(a) - omg_as_int(b);
}

function omg_mul(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        return omg_as_float(a) * omg_as_float(b);
    }
    return omg_as_int(a) * omg_as_int(b);
}

// `/`: any-float → true division (Number). int÷int → floor division
// (BigInt) to match OMG VM (`-7 / 2 == -4`).
function omg_div(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        const bd = omg_as_float(b);
        if (bd === 0) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
        return omg_as_float(a) / bd;
    }
    const x = omg_as_int(a), y = omg_as_int(b);
    if (y === 0n) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
    let q = x / y;
    if ((x % y !== 0n) && ((x < 0n) !== (y < 0n))) q -= 1n;
    return q;
}

function omg_floor_div(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        const bd = omg_as_float(b);
        if (bd === 0) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
        return Math.floor(omg_as_float(a) / bd);
    }
    const x = omg_as_int(a), y = omg_as_int(b);
    if (y === 0n) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
    let q = x / y;
    if ((x % y !== 0n) && ((x < 0n) !== (y < 0n))) q -= 1n;
    return q;
}

function omg_mod(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        const bd = omg_as_float(b);
        if (bd === 0) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
        const ad = omg_as_float(a);
        return ad - Math.floor(ad / bd) * bd;
    }
    const x = omg_as_int(a), y = omg_as_int(b);
    if (y === 0n) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
    let r = x % y;
    if (r !== 0n && ((r < 0n) !== (y < 0n))) r += y;
    return r;
}

function omg_neg(a) {
    if (typeof a === 'number') return -a;
    return -omg_as_int(a);
}

// === Comparisons ===========================================================

function omg_values_equal(a, b) {
    // Cross-type numeric: int↔float compare by value (matches Rust).
    if ((typeof a === 'bigint' && typeof b === 'number') ||
        (typeof a === 'number' && typeof b === 'bigint')) {
        return omg_as_float(a) === omg_as_float(b);
    }
    if (typeof a !== typeof b && !(Array.isArray(a) && Array.isArray(b)) && !(a instanceof Map && b instanceof Map)) {
        return false;
    }
    if (Array.isArray(a) && Array.isArray(b)) {
        if (a.length !== b.length) return false;
        for (let i = 0; i < a.length; i++) {
            if (!omg_values_equal(a[i], b[i])) return false;
        }
        return true;
    }
    if (a instanceof Map && b instanceof Map) {
        if (a.size !== b.size) return false;
        for (const [k, v] of a) {
            if (!b.has(k)) return false;
            if (!omg_values_equal(v, b.get(k))) return false;
        }
        return true;
    }
    return a === b;
}

function omg_eq(a, b) { return omg_values_equal(a, b); }
function omg_ne(a, b) { return !omg_values_equal(a, b); }

function omg_compare(a, b) {
    if (typeof a === 'string' && typeof b === 'string') {
        if (a < b) return -1;
        if (a > b) return 1;
        return 0;
    }
    if (typeof a === 'number' || typeof b === 'number') {
        const x = omg_as_float(a), y = omg_as_float(b);
        if (x < y) return -1;
        if (x > y) return 1;
        return 0;
    }
    const x = omg_as_int(a), y = omg_as_int(b);
    if (x < y) return -1;
    if (x > y) return 1;
    return 0;
}

function omg_lt(a, b) { return omg_compare(a, b) <  0; }
function omg_le(a, b) { return omg_compare(a, b) <= 0; }
function omg_gt(a, b) { return omg_compare(a, b) >  0; }
function omg_ge(a, b) { return omg_compare(a, b) >= 0; }

// === Bitwise ===============================================================

function _reject_float(v, op) {
    if (typeof v === 'number') {
        omg_panic('TypeError', "operator '" + op + "' is not defined for floats");
    }
}

function omg_band(a, b) { _reject_float(a, '&'); _reject_float(b, '&');
                          return omg_as_int(a) & omg_as_int(b); }
function omg_bor (a, b) { _reject_float(a, '|'); _reject_float(b, '|');
                          return omg_as_int(a) | omg_as_int(b); }
function omg_bxor(a, b) { _reject_float(a, '^'); _reject_float(b, '^');
                          return omg_as_int(a) ^ omg_as_int(b); }
function omg_shl (a, b) {
    _reject_float(a, '<<'); _reject_float(b, '<<');
    const ai = omg_as_int(a), bi = omg_as_int(b);
    if (bi < 0n || bi >= 64n) omg_panic('ValueError', 'shift count out of range: ' + bi);
    return BigInt.asIntN(64, ai << bi);
}
function omg_shr (a, b) {
    _reject_float(a, '>>'); _reject_float(b, '>>');
    const ai = omg_as_int(a), bi = omg_as_int(b);
    if (bi < 0n || bi >= 64n) omg_panic('ValueError', 'shift count out of range: ' + bi);
    return ai >> bi;
}
function omg_bnot(a) { _reject_float(a, '~'); return ~omg_as_int(a); }

// === Indexing / slicing ====================================================

function _norm_idx(i, n, what) {
    let r = (i < 0) ? i + BigInt(n) : i;
    if (r < 0n || r >= BigInt(n)) {
        omg_panic('IndexError', 'index ' + i + ' out of range for length ' + n);
    }
    return Number(r);
}

function omg_index(base, idx) {
    if (typeof base === 'string') {
        if (typeof idx !== 'bigint') omg_panic('TypeError', 'string index must be int');
        const r = _norm_idx(idx, base.length, 'string');
        return base[r];
    }
    if (Array.isArray(base)) {
        if (typeof idx !== 'bigint') omg_panic('TypeError', 'list index must be int');
        const r = _norm_idx(idx, base.length, 'list');
        return base[r];
    }
    if (base instanceof Map) {
        const key = (typeof idx === 'string') ? idx : omg_to_string(idx);
        if (!base.has(key)) omg_panic('KeyError', "Key '" + key + "' not found");
        return base.get(key);
    }
    omg_panic('TypeError', 'cannot index value');
}

function omg_index_set(base, idx, val) {
    if (Array.isArray(base)) {
        if (typeof idx !== 'bigint') omg_panic('TypeError', 'list index must be int');
        const r = _norm_idx(idx, base.length, 'list');
        base[r] = val;
        return;
    }
    if (base instanceof Map) {
        const key = (typeof idx === 'string') ? idx : omg_to_string(idx);
        if (base.__omg_frozen) omg_panic('FrozenWriteError', 'Imported modules are read-only');
        base.set(key, val);
        return;
    }
    omg_panic('TypeError', 'cannot assign to index of value');
}

function omg_slice(base, start_v, end_v) {
    let n;
    if (typeof base === 'string') n = base.length;
    else if (Array.isArray(base)) n = base.length;
    else omg_panic('TypeError', 'cannot slice value');

    let start = (start_v === null) ? 0 : Number(omg_as_int(start_v));
    let end   = (end_v   === null) ? n : Number(omg_as_int(end_v));
    if (start < 0) start += n;
    if (end   < 0) end   += n;
    if (start < 0) start = 0;
    if (end   > n) end   = n;
    if (start > end) start = end;
    return base.slice(start, end);
}

function omg_attr(base, name) {
    if (base instanceof Map) {
        if (!base.has(name)) omg_panic('KeyError', "Key '" + name + "' not found");
        return base.get(name);
    }
    omg_panic('TypeError', 'cannot read attribute of value');
}

function omg_attr_set(base, name, val) {
    if (base instanceof Map) {
        if (base.__omg_frozen) omg_panic('FrozenWriteError', 'Imported modules are read-only');
        base.set(name, val);
        return;
    }
    omg_panic('TypeError', 'cannot assign attribute of value');
}

// === Builtins ==============================================================

function omg_length(v) {
    if (typeof v === 'string') {
        // OMG strings are byte-counted? Actually OMG uses code-point
        // count for strings (see omg_rt.h's omg_str_char_count). For
        // ASCII-only text these match; for now just use JS string
        // length which counts UTF-16 code units. Refine if a parity
        // test surfaces a divergence on multi-byte text.
        return BigInt(v.length);
    }
    if (Array.isArray(v)) return BigInt(v.length);
    if (v instanceof Map)  return BigInt(v.size);
    omg_panic('TypeError', 'length() expects a string, list, or dict');
}

function omg_chr(n) {
    const i = Number(omg_as_int(n));
    return String.fromCharCode(i);
}
function omg_ascii(s) {
    if (typeof s !== 'string' || s.length !== 1) {
        omg_panic('TypeError', 'ascii() expects a one-character string');
    }
    return BigInt(s.charCodeAt(0));
}
function omg_int(v)   { return omg_as_int(v); }
function omg_float(v) { return omg_as_float(v); }
function omg_floor(v) { return BigInt(Math.floor(omg_as_float(v))); }
function omg_ceil(v)  { return BigInt(Math.ceil (omg_as_float(v))); }
function omg_round(v) {
    // Banker's rounding to match Rust's f64 round-half-to-even.
    const x = omg_as_float(v);
    const r = Math.round(x);
    if (Math.abs(x - Math.trunc(x)) === 0.5 && (Math.trunc(x) & 1) === 0) {
        return BigInt(r - Math.sign(x));
    }
    return BigInt(r);
}
function omg_abs(v) {
    if (typeof v === 'bigint') return v < 0n ? -v : v;
    if (typeof v === 'number') return Math.abs(v);
    omg_panic('TypeError', 'abs() expects a number');
}
function omg_sqrt(v) { return Math.sqrt(omg_as_float(v)); }
function omg_pow(a, b) {
    if (typeof a === 'bigint' && typeof b === 'bigint' && b >= 0n) {
        return a ** b;
    }
    return Math.pow(omg_as_float(a), omg_as_float(b));
}
function omg_log(v) { return Math.log(omg_as_float(v)); }
function omg_sin(v) { return Math.sin(omg_as_float(v)); }
function omg_cos(v) { return Math.cos(omg_as_float(v)); }
function omg_tan(v) { return Math.tan(omg_as_float(v)); }

function omg_hex(n) {
    let i = omg_as_int(n);
    if (i < 0n) return '-' + (-i).toString(16);
    return i.toString(16);
}
function omg_binary(n, w) {
    let i = omg_as_int(n);
    let s;
    if (i < 0n) s = '-' + (-i).toString(2);
    else s = i.toString(2);
    if (w !== undefined) {
        const width = Number(omg_as_int(w));
        // Pad without sign if positive; if negative we leave as-is
        // (matches OMG which doesn't sign-extend the binary builtin).
        while (s.length < width) s = '0' + s;
    }
    return s;
}

function omg_freeze(d) {
    if (!(d instanceof Map)) omg_panic('TypeError', 'freeze() expects a dict');
    d.__omg_frozen = true;
    return d;
}

function omg_dict_keys(d) {
    if (!(d instanceof Map)) omg_panic('TypeError', 'dict_keys() expects a dict');
    return Array.from(d.keys());
}

function omg_string_bytes(s) {
    if (typeof s !== 'string') omg_panic('TypeError', 'string_bytes() expects a string');
    const enc = new TextEncoder();
    return Array.from(enc.encode(s)).map(b => BigInt(b));
}
function omg_bytes_to_string(bs) {
    if (!Array.isArray(bs)) omg_panic('TypeError', 'bytes_to_string() expects a list of bytes');
    const buf = new Uint8Array(bs.length);
    for (let i = 0; i < bs.length; i++) buf[i] = Number(omg_as_int(bs[i]));
    return new TextDecoder().decode(buf);
}

function omg_float_bits(s) {
    if (typeof s !== 'string') omg_panic('TypeError', 'float_bits() expects a string');
    const f = parseFloat(s);
    const buf = new ArrayBuffer(8);
    new DataView(buf).setFloat64(0, f, true);
    return new DataView(buf).getBigInt64(0, true);
}
function omg_bits_to_float(i) {
    const bi = omg_as_int(i);
    const buf = new ArrayBuffer(8);
    new DataView(buf).setBigInt64(0, bi, true);
    return new DataView(buf).getFloat64(0, true);
}

// === Exit / process control ================================================
// In node these have real implementations; in the browser the
// playground overrides them.

let _omg_exit = (code) => { if (typeof process !== 'undefined') process.exit(Number(code)); };
function omg_exit(code) { _omg_exit(omg_as_int(code)); }
function omg_exit_with_error(msg) {
    if (typeof msg !== 'string') msg = omg_to_string(msg);
    if (typeof process !== 'undefined') {
        process.stderr.write(msg + '\n');
        process.exit(1);
    } else {
        throw new OmgError('Exit', msg);
    }
}
function omg_panic_user(msg) { omg_panic('RuntimeError', omg_to_string(msg)); }

// === File I/O (node-only) =================================================
// In a browser context these all panic with a friendly message; the
// playground can override _omg_fs with a virtual FS if it wants
// programs that touch files to work.

let _omg_fs = null;
if (typeof require !== 'undefined') {
    try { _omg_fs = require('fs'); } catch (_e) { _omg_fs = null; }
}

function _need_fs(name) {
    if (!_omg_fs) {
        omg_panic('TypeError', name + '() requires file I/O (node-only)');
    }
}

function omg_read_file(path) {
    _need_fs('read_file');
    try {
        return _omg_fs.readFileSync(path, 'utf8');
    } catch (_e) {
        return false;
    }
}

function omg_file_exists(path) {
    _need_fs('file_exists');
    return _omg_fs.existsSync(path);
}

function omg_is_dir(path) {
    _need_fs('is_dir');
    try { return _omg_fs.statSync(path).isDirectory(); } catch (_e) { return false; }
}

function omg_read_dir(path) {
    _need_fs('read_dir');
    try {
        return _omg_fs.readdirSync(path).sort().filter(n => n !== '.' && n !== '..');
    } catch (_e) {
        return [];
    }
}

function omg_make_dir(path) {
    _need_fs('make_dir');
    try { _omg_fs.mkdirSync(path, { recursive: true }); return true; }
    catch (_e) { return false; }
}

// File handles for stream I/O. We implement a tiny in-memory buffer
// model (read whole file at open, write to a buffer flushed at close).
// Mode is one of r/rb/w/wb/a/ab/rb+/wb+ — matches omg_rt.h.
const _omg_handles = new Map();
let _omg_next_fd = 1;

function omg_file_open(path, mode) {
    _need_fs('file_open');
    if (typeof path !== 'string' || typeof mode !== 'string') {
        omg_panic('TypeError', 'file_open() expects path and mode');
    }
    const binary = mode.includes('b');
    const fd = _omg_next_fd++;
    let buf;
    if (mode === 'r' || mode === 'rb' || mode === 'rb+') {
        try {
            buf = _omg_fs.readFileSync(path);
        } catch (_e) {
            omg_panic('ValueError', "cannot open '" + path + "': " + _e.message);
        }
    } else if (mode === 'w' || mode === 'wb' || mode === 'wb+') {
        buf = Buffer.alloc(0);
    } else if (mode === 'a' || mode === 'ab') {
        try { buf = _omg_fs.readFileSync(path); } catch (_e) { buf = Buffer.alloc(0); }
    } else {
        omg_panic('ValueError', 'invalid file mode');
    }
    _omg_handles.set(fd, { path, mode, binary, buf, pos: (mode === 'a' || mode === 'ab') ? buf.length : 0 });
    return BigInt(fd);
}

function omg_file_read(handle) {
    const h = _omg_handles.get(Number(omg_as_int(handle)));
    if (!h) omg_panic('ValueError', 'invalid file handle');
    const slice = h.buf.subarray(h.pos);
    h.pos = h.buf.length;
    if (h.binary) return Array.from(slice).map(b => BigInt(b));
    return slice.toString('utf8');
}

function omg_file_write(handle, data) {
    const h = _omg_handles.get(Number(omg_as_int(handle)));
    if (!h) omg_panic('ValueError', 'invalid file handle');
    let chunk;
    if (h.binary) {
        if (!Array.isArray(data)) omg_panic('TypeError', 'file_write() binary handle expects list');
        chunk = Buffer.from(data.map(v => Number(omg_as_int(v))));
    } else {
        if (typeof data !== 'string') omg_panic('TypeError', 'file_write() text handle expects string');
        chunk = Buffer.from(data, 'utf8');
    }
    if (h.pos < h.buf.length) {
        // Overwrite in place, growing if needed.
        const need = h.pos + chunk.length;
        if (need > h.buf.length) {
            const nb = Buffer.alloc(need);
            h.buf.copy(nb, 0, 0, h.buf.length);
            h.buf = nb;
        }
        chunk.copy(h.buf, h.pos);
    } else {
        h.buf = Buffer.concat([h.buf, chunk]);
    }
    h.pos += chunk.length;
    return BigInt(chunk.length);
}

function omg_file_close(handle) {
    const fd = Number(omg_as_int(handle));
    const h = _omg_handles.get(fd);
    if (!h) omg_panic('ValueError', 'invalid file handle');
    if (h.mode !== 'r' && h.mode !== 'rb') {
        try { _omg_fs.writeFileSync(h.path, h.buf); }
        catch (_e) { omg_panic('ValueError', 'cannot write ' + h.path + ': ' + _e.message); }
    }
    _omg_handles.delete(fd);
    return null;
}

function omg_file_seek(handle, offset) {
    const h = _omg_handles.get(Number(omg_as_int(handle)));
    if (!h) omg_panic('ValueError', 'invalid file handle');
    const off = Number(omg_as_int(offset));
    if (off < 0) omg_panic('ValueError', 'file_seek() expects a non-negative offset');
    h.pos = off;
    return BigInt(off);
}

function omg_file_tell(handle) {
    const h = _omg_handles.get(Number(omg_as_int(handle)));
    if (!h) omg_panic('ValueError', 'invalid file handle');
    return BigInt(h.pos);
}

// === Stdin / process control (node-only) =================================

function omg_stdin_readline() {
    if (typeof require === 'undefined') return false;
    // Synchronous one-line stdin read via fs.readFileSync('/dev/stdin').
    // Cached on first call so subsequent calls walk lines from the cache.
    if (!omg_stdin_readline._buf) {
        try {
            omg_stdin_readline._buf = _omg_fs.readFileSync(0, 'utf8');
            omg_stdin_readline._pos = 0;
        } catch (_e) {
            omg_stdin_readline._buf = '';
            omg_stdin_readline._pos = 0;
        }
    }
    const buf = omg_stdin_readline._buf;
    let pos = omg_stdin_readline._pos;
    if (pos >= buf.length) return false;
    const nl = buf.indexOf('\n', pos);
    let line;
    if (nl < 0) { line = buf.slice(pos); omg_stdin_readline._pos = buf.length; }
    else { line = buf.slice(pos, nl); omg_stdin_readline._pos = nl + 1; }
    if (line.endsWith('\r')) line = line.slice(0, -1);
    return line;
}

function omg_stdin_read() {
    if (typeof require === 'undefined') return '';
    try { return _omg_fs.readFileSync(0, 'utf8'); }
    catch (_e) { return ''; }
}

function omg_stdin_read_bytes() {
    if (typeof require === 'undefined') return [];
    try { return Array.from(_omg_fs.readFileSync(0)).map(b => BigInt(b)); }
    catch (_e) { return []; }
}

function omg_subprocess(argv) {
    if (typeof require === 'undefined') {
        omg_panic('TypeError', 'subprocess() requires node');
    }
    const { spawnSync } = require('child_process');
    if (!Array.isArray(argv)) omg_panic('TypeError', 'subprocess() expects a list');
    const cmd = argv[0];
    const args = argv.slice(1);
    const r = spawnSync(cmd, args, { stdio: 'inherit' });
    if (r.error) omg_panic('ValueError', 'subprocess: ' + r.error.message);
    return BigInt(r.status === null ? 128 + (r.signal === 'SIGINT' ? 2 : 1) : r.status);
}

function omg_getpid() {
    return BigInt(typeof process !== 'undefined' ? process.pid : 0);
}

function omg_executable_path() {
    return typeof process !== 'undefined' ? process.argv[0] : false;
}

// === call_builtin: dynamic dispatch =======================================
// Used by some advanced features (the OMG-in-OMG interpreter, error
// helpers). Maps name → handler.

const _omg_builtins = {
    chr: omg_chr,
    ascii: omg_ascii,
    int: omg_int,
    float: omg_float,
    floor: omg_floor,
    ceil: omg_ceil,
    round: omg_round,
    abs: omg_abs,
    sqrt: omg_sqrt,
    pow: omg_pow,
    log: omg_log,
    sin: omg_sin,
    cos: omg_cos,
    tan: omg_tan,
    hex: omg_hex,
    binary: omg_binary,
    length: omg_length,
    freeze: omg_freeze,
    dict_keys: omg_dict_keys,
    string_bytes: omg_string_bytes,
    bytes_to_string: omg_bytes_to_string,
    float_bits: omg_float_bits,
    bits_to_float: omg_bits_to_float,
    panic: omg_panic_user,
    raise: omg_panic_user,
    exit: omg_exit,
    exit_with_error: omg_exit_with_error,
    print: omg_print,
    read_file: omg_read_file,
    file_open: omg_file_open,
    file_read: omg_file_read,
    file_write: omg_file_write,
    file_close: omg_file_close,
    file_seek: omg_file_seek,
    file_tell: omg_file_tell,
    file_exists: omg_file_exists,
    is_dir: omg_is_dir,
    read_dir: omg_read_dir,
    make_dir: omg_make_dir,
    stdin_readline: omg_stdin_readline,
    stdin_read: omg_stdin_read,
    stdin_read_bytes: omg_stdin_read_bytes,
    subprocess: omg_subprocess,
    getpid: omg_getpid,
    executable_path: omg_executable_path,
};

function omg_call_builtin(name, args) {
    const fn = _omg_builtins[name];
    if (!fn) omg_panic('TypeError', 'unknown builtin: ' + name);
    return fn(...args);
}
_omg_builtins.call_builtin = omg_call_builtin;

// === Closure helper =======================================================

function omg_closure(fn, captured) {
    const wrapped = (...args) => fn(captured, ...args);
    wrapped.__omg_captured = captured;
    return wrapped;
}

// String-named function table. Populated by the program preamble
// after every top-level MAKE_FUNC, so that CALL_VALUE on a string
// (which is what import-module dispatch produces) can resolve it.
const omg_func_table = new Map();
function omg_lookup_fn(name) {
    const fn = omg_func_table.get(name);
    if (!fn) omg_panic('UndefinedIdentError', name);
    return fn;
}

// Default-injected globals. Programs may shadow these.
const args = (typeof process !== 'undefined') ? process.argv.slice(1) : [];
let module_file = '';
let current_dir = (typeof process !== 'undefined') ? process.cwd() : '/';

// === Program ==============================================================

let v_program;
let v_ptr;
let v_instr;
let v_stack;
let v_memory;
let v_labels;
let v_store_var;
let v_load_var;
let v_idx;
let v_find_label;
let v__;
let v_lhs;
let v_rhs;
let v_op;
let v_val;
let v_cond;

function omg_p0(_captured, v_label) {
    let v_j;
    let v_entry;
    const _s = [];
    let _ip = 626;
    let _eh = [];
    while (true) {
        switch (_ip) {
        case 626: {
    _s.push(0n);
        }
        // fall through to 627
        case 627: {
    v_j = _s.pop();
        }
        // fall through to 628
        case 628: {
    _s.push(v_j);
        }
        // fall through to 629
        case 629: {
    _s.push(v_labels);
        }
        // fall through to 630
        case 630: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 631
        case 631: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
        }
        // fall through to 632
        case 632: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 653; continue; } }
        }
        // fall through to 633
        case 633: {
    _s.push(v_labels);
        }
        // fall through to 634
        case 634: {
    _s.push(v_j);
        }
        // fall through to 635
        case 635: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 636
        case 636: {
    v_entry = _s.pop();
        }
        // fall through to 637
        case 637: {
    _s.push(v_entry);
        }
        // fall through to 638
        case 638: {
    _s.push(0n);
        }
        // fall through to 639
        case 639: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 640
        case 640: {
    _s.push(v_label);
        }
        // fall through to 641
        case 641: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 642
        case 642: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 648; continue; } }
        }
        // fall through to 643
        case 643: {
    _s.push(v_entry);
        }
        // fall through to 644
        case 644: {
    _s.push(1n);
        }
        // fall through to 645
        case 645: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 646
        case 646: {
    return _s.pop();
        }
        // fall through to 647
        case 647: {
    _ip = 648; continue;
        }
        // fall through to 648
        case 648: {
    _s.push(v_j);
        }
        // fall through to 649
        case 649: {
    _s.push(1n);
        }
        // fall through to 650
        case 650: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 651
        case 651: {
    v_j = _s.pop();
        }
        // fall through to 652
        case 652: {
    _ip = 628; continue;
        }
        // fall through to 653
        case 653: {
    _s.push("Missing label: ");
        }
        // fall through to 654
        case 654: {
    _s.push(v_label);
        }
        // fall through to 655
        case 655: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 656
        case 656: {
    omg_emit(_s.pop());
        }
        // fall through to 657
        case 657: {
    _s.push(0n);
        }
        // fall through to 658
        case 658: {
    return _s.pop();
        }
        // fall through to 659
        case 659: {
    _s.push(null);
        }
        // fall through to 660
        case 660: {
    return _s.pop();
        }
        // fall through to 661
        default: return;
        }
        _ip += 1;
    }
}

function omg_p1(_captured, v_name) {
    let v_i;
    let v_entry;
    let v_key;
    const _s = [];
    let _ip = 589;
    let _eh = [];
    while (true) {
        switch (_ip) {
        case 589: {
    _s.push(0n);
        }
        // fall through to 590
        case 590: {
    v_i = _s.pop();
        }
        // fall through to 591
        case 591: {
    _s.push(v_i);
        }
        // fall through to 592
        case 592: {
    _s.push(v_memory);
        }
        // fall through to 593
        case 593: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 594
        case 594: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
        }
        // fall through to 595
        case 595: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 618; continue; } }
        }
        // fall through to 596
        case 596: {
    _s.push(v_memory);
        }
        // fall through to 597
        case 597: {
    _s.push(v_i);
        }
        // fall through to 598
        case 598: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 599
        case 599: {
    v_entry = _s.pop();
        }
        // fall through to 600
        case 600: {
    _s.push(v_entry);
        }
        // fall through to 601
        case 601: {
    _s.push(0n);
        }
        // fall through to 602
        case 602: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 603
        case 603: {
    v_key = _s.pop();
        }
        // fall through to 604
        case 604: {
    _s.push(v_key);
        }
        // fall through to 605
        case 605: {
    _s.push(v_name);
        }
        // fall through to 606
        case 606: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 607
        case 607: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 613; continue; } }
        }
        // fall through to 608
        case 608: {
    _s.push(v_entry);
        }
        // fall through to 609
        case 609: {
    _s.push(1n);
        }
        // fall through to 610
        case 610: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 611
        case 611: {
    return _s.pop();
        }
        // fall through to 612
        case 612: {
    _ip = 613; continue;
        }
        // fall through to 613
        case 613: {
    _s.push(v_i);
        }
        // fall through to 614
        case 614: {
    _s.push(1n);
        }
        // fall through to 615
        case 615: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 616
        case 616: {
    v_i = _s.pop();
        }
        // fall through to 617
        case 617: {
    _ip = 591; continue;
        }
        // fall through to 618
        case 618: {
    _s.push("Undefined variable: ");
        }
        // fall through to 619
        case 619: {
    _s.push(v_name);
        }
        // fall through to 620
        case 620: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 621
        case 621: {
    omg_emit(_s.pop());
        }
        // fall through to 622
        case 622: {
    _s.push(0n);
        }
        // fall through to 623
        case 623: {
    return _s.pop();
        }
        // fall through to 624
        case 624: {
    _s.push(null);
        }
        // fall through to 625
        case 625: {
    return _s.pop();
        }
        // fall through to 626
        default: return;
        }
        _ip += 1;
    }
}

function omg_p2(_captured, v_name, v_val) {
    let v_i;
    let v_entry;
    let v_key;
    let v_new_entry;
    let v_pair;
    const _s = [];
    let _ip = 529;
    let _eh = [];
    while (true) {
        switch (_ip) {
        case 529: {
    _s.push(0n);
        }
        // fall through to 530
        case 530: {
    v_i = _s.pop();
        }
        // fall through to 531
        case 531: {
    _s.push(v_i);
        }
        // fall through to 532
        case 532: {
    _s.push(v_memory);
        }
        // fall through to 533
        case 533: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 534
        case 534: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
        }
        // fall through to 535
        case 535: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 576; continue; } }
        }
        // fall through to 536
        case 536: {
    _s.push(v_memory);
        }
        // fall through to 537
        case 537: {
    _s.push(v_i);
        }
        // fall through to 538
        case 538: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 539
        case 539: {
    v_entry = _s.pop();
        }
        // fall through to 540
        case 540: {
    _s.push(v_entry);
        }
        // fall through to 541
        case 541: {
    _s.push(0n);
        }
        // fall through to 542
        case 542: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 543
        case 543: {
    v_key = _s.pop();
        }
        // fall through to 544
        case 544: {
    _s.push(v_key);
        }
        // fall through to 545
        case 545: {
    _s.push(v_name);
        }
        // fall through to 546
        case 546: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 547
        case 547: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 571; continue; } }
        }
        // fall through to 548
        case 548: {
    _s.push(v_name);
        }
        // fall through to 549
        case 549: {
    _s.push(v_val);
        }
        // fall through to 550
        case 550: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
        }
        // fall through to 551
        case 551: {
    v_new_entry = _s.pop();
        }
        // fall through to 552
        case 552: {
    _s.push(v_memory);
        }
        // fall through to 553
        case 553: {
    _s.push(0n);
        }
        // fall through to 554
        case 554: {
    _s.push(v_i);
        }
        // fall through to 555
        case 555: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
        }
        // fall through to 556
        case 556: {
    _s.push(v_new_entry);
        }
        // fall through to 557
        case 557: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 558
        case 558: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 559
        case 559: {
    _s.push(v_memory);
        }
        // fall through to 560
        case 560: {
    _s.push(v_i);
        }
        // fall through to 561
        case 561: {
    _s.push(1n);
        }
        // fall through to 562
        case 562: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 563
        case 563: {
    _s.push(v_memory);
        }
        // fall through to 564
        case 564: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 565
        case 565: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
        }
        // fall through to 566
        case 566: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 567
        case 567: {
    v_memory = _s.pop();
        }
        // fall through to 568
        case 568: {
    _s.push(v_memory);
        }
        // fall through to 569
        case 569: {
    return _s.pop();
        }
        // fall through to 570
        case 570: {
    _ip = 571; continue;
        }
        // fall through to 571
        case 571: {
    _s.push(v_i);
        }
        // fall through to 572
        case 572: {
    _s.push(1n);
        }
        // fall through to 573
        case 573: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 574
        case 574: {
    v_i = _s.pop();
        }
        // fall through to 575
        case 575: {
    _ip = 531; continue;
        }
        // fall through to 576
        case 576: {
    _s.push(v_name);
        }
        // fall through to 577
        case 577: {
    _s.push(v_val);
        }
        // fall through to 578
        case 578: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
        }
        // fall through to 579
        case 579: {
    v_pair = _s.pop();
        }
        // fall through to 580
        case 580: {
    _s.push(v_memory);
        }
        // fall through to 581
        case 581: {
    _s.push(v_pair);
        }
        // fall through to 582
        case 582: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 583
        case 583: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 584
        case 584: {
    v_memory = _s.pop();
        }
        // fall through to 585
        case 585: {
    _s.push(v_memory);
        }
        // fall through to 586
        case 586: {
    return _s.pop();
        }
        // fall through to 587
        case 587: {
    _s.push(null);
        }
        // fall through to 588
        case 588: {
    return _s.pop();
        }
        // fall through to 589
        default: return;
        }
        _ip += 1;
    }
}

omg_func_table.set("find_label", omg_p0);
omg_func_table.set("load_var", omg_p1);
omg_func_table.set("store_var", omg_p2);

try {
(function _omg_main() {
    const _s = [];
    let _ip = 0;
    let _eh = [];
    while (true) {
        switch (_ip) {
        case 0: {
    _s.push("push");
        }
        // fall through to 1
        case 1: {
    _s.push(5n);
        }
        // fall through to 2
        case 2: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
        }
        // fall through to 3
        case 3: {
    _s.push("push");
        }
        // fall through to 4
        case 4: {
    _s.push(3n);
        }
        // fall through to 5
        case 5: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
        }
        // fall through to 6
        case 6: {
    _s.push("add");
        }
        // fall through to 7
        case 7: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 8
        case 8: {
    _s.push("store");
        }
        // fall through to 9
        case 9: {
    _s.push("x");
        }
        // fall through to 10
        case 10: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
        }
        // fall through to 11
        case 11: {
    _s.push("push");
        }
        // fall through to 12
        case 12: {
    _s.push(10n);
        }
        // fall through to 13
        case 13: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
        }
        // fall through to 14
        case 14: {
    _s.push("load");
        }
        // fall through to 15
        case 15: {
    _s.push("x");
        }
        // fall through to 16
        case 16: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
        }
        // fall through to 17
        case 17: {
    _s.push("mul");
        }
        // fall through to 18
        case 18: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 19
        case 19: {
    _s.push("emit_top");
        }
        // fall through to 20
        case 20: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 21
        case 21: {
    _s.push("pop");
        }
        // fall through to 22
        case 22: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 23
        case 23: {
    _s.push("label");
        }
        // fall through to 24
        case 24: {
    _s.push("loop");
        }
        // fall through to 25
        case 25: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
        }
        // fall through to 26
        case 26: {
    _s.push("load");
        }
        // fall through to 27
        case 27: {
    _s.push("x");
        }
        // fall through to 28
        case 28: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
        }
        // fall through to 29
        case 29: {
    _s.push("push");
        }
        // fall through to 30
        case 30: {
    _s.push(1n);
        }
        // fall through to 31
        case 31: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
        }
        // fall through to 32
        case 32: {
    _s.push("sub");
        }
        // fall through to 33
        case 33: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 34
        case 34: {
    _s.push("store");
        }
        // fall through to 35
        case 35: {
    _s.push("x");
        }
        // fall through to 36
        case 36: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
        }
        // fall through to 37
        case 37: {
    _s.push("load");
        }
        // fall through to 38
        case 38: {
    _s.push("x");
        }
        // fall through to 39
        case 39: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
        }
        // fall through to 40
        case 40: {
    _s.push("jmp_if_nonzero");
        }
        // fall through to 41
        case 41: {
    _s.push("loop");
        }
        // fall through to 42
        case 42: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
        }
        // fall through to 43
        case 43: {
    _s.push("halt");
        }
        // fall through to 44
        case 44: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 45
        case 45: {
    { const _arr = _s.splice(_s.length - 17, 17); _s.push(_arr); }
        }
        // fall through to 46
        case 46: {
    v_program = _s.pop();
        }
        // fall through to 47
        case 47: {
    _s.push(0n);
        }
        // fall through to 48
        case 48: {
    v_ptr = _s.pop();
        }
        // fall through to 49
        case 49: {
    { const _arr = _s.splice(_s.length - 0, 0); _s.push(_arr); }
        }
        // fall through to 50
        case 50: {
    v_instr = _s.pop();
        }
        // fall through to 51
        case 51: {
    { const _arr = _s.splice(_s.length - 0, 0); _s.push(_arr); }
        }
        // fall through to 52
        case 52: {
    v_stack = _s.pop();
        }
        // fall through to 53
        case 53: {
    { const _arr = _s.splice(_s.length - 0, 0); _s.push(_arr); }
        }
        // fall through to 54
        case 54: {
    v_memory = _s.pop();
        }
        // fall through to 55
        case 55: {
    { const _arr = _s.splice(_s.length - 0, 0); _s.push(_arr); }
        }
        // fall through to 56
        case 56: {
    v_labels = _s.pop();
        }
        // fall through to 57
        case 57: {
    {
        const _cap = new Map();
        v_store_var = (...args) => omg_p2(_cap, ...args);
    }
        }
        // fall through to 58
        case 58: {
    {
        const _cap = new Map();
        v_load_var = (...args) => omg_p1(_cap, ...args);
    }
        }
        // fall through to 59
        case 59: {
    _s.push(0n);
        }
        // fall through to 60
        case 60: {
    v_idx = _s.pop();
        }
        // fall through to 61
        case 61: {
    _s.push(v_idx);
        }
        // fall through to 62
        case 62: {
    _s.push(v_program);
        }
        // fall through to 63
        case 63: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 64
        case 64: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
        }
        // fall through to 65
        case 65: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 91; continue; } }
        }
        // fall through to 66
        case 66: {
    _s.push(v_program);
        }
        // fall through to 67
        case 67: {
    _s.push(v_idx);
        }
        // fall through to 68
        case 68: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 69
        case 69: {
    v_instr = _s.pop();
        }
        // fall through to 70
        case 70: {
    _s.push(v_instr);
        }
        // fall through to 71
        case 71: {
    _s.push(0n);
        }
        // fall through to 72
        case 72: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 73
        case 73: {
    _s.push("label");
        }
        // fall through to 74
        case 74: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 75
        case 75: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 86; continue; } }
        }
        // fall through to 76
        case 76: {
    _s.push(v_labels);
        }
        // fall through to 77
        case 77: {
    _s.push(v_instr);
        }
        // fall through to 78
        case 78: {
    _s.push(1n);
        }
        // fall through to 79
        case 79: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 80
        case 80: {
    _s.push(v_idx);
        }
        // fall through to 81
        case 81: {
    { const _arr = _s.splice(_s.length - 2, 2); _s.push(_arr); }
        }
        // fall through to 82
        case 82: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 83
        case 83: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 84
        case 84: {
    v_labels = _s.pop();
        }
        // fall through to 85
        case 85: {
    _ip = 86; continue;
        }
        // fall through to 86
        case 86: {
    _s.push(v_idx);
        }
        // fall through to 87
        case 87: {
    _s.push(1n);
        }
        // fall through to 88
        case 88: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 89
        case 89: {
    v_idx = _s.pop();
        }
        // fall through to 90
        case 90: {
    _ip = 61; continue;
        }
        // fall through to 91
        case 91: {
    {
        const _cap = new Map();
        v_find_label = (...args) => omg_p0(_cap, ...args);
    }
        }
        // fall through to 92
        case 92: {
    _s.push(false);
        }
        // fall through to 93
        case 93: {
    v__ = _s.pop();
        }
        // fall through to 94
        case 94: {
    _s.push(false);
        }
        // fall through to 95
        case 95: {
    v_lhs = _s.pop();
        }
        // fall through to 96
        case 96: {
    _s.push(false);
        }
        // fall through to 97
        case 97: {
    v_rhs = _s.pop();
        }
        // fall through to 98
        case 98: {
    _s.push(false);
        }
        // fall through to 99
        case 99: {
    v_op = _s.pop();
        }
        // fall through to 100
        case 100: {
    _s.push(false);
        }
        // fall through to 101
        case 101: {
    v_val = _s.pop();
        }
        // fall through to 102
        case 102: {
    _s.push(false);
        }
        // fall through to 103
        case 103: {
    v_cond = _s.pop();
        }
        // fall through to 104
        case 104: {
    _s.push(v_ptr);
        }
        // fall through to 105
        case 105: {
    _s.push(v_program);
        }
        // fall through to 106
        case 106: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 107
        case 107: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
        }
        // fall through to 108
        case 108: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 528; continue; } }
        }
        // fall through to 109
        case 109: {
    _s.push(v_program);
        }
        // fall through to 110
        case 110: {
    _s.push(v_ptr);
        }
        // fall through to 111
        case 111: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 112
        case 112: {
    v_instr = _s.pop();
        }
        // fall through to 113
        case 113: {
    _s.push(v_ptr);
        }
        // fall through to 114
        case 114: {
    _s.push(1n);
        }
        // fall through to 115
        case 115: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 116
        case 116: {
    v_ptr = _s.pop();
        }
        // fall through to 117
        case 117: {
    _s.push(v_instr);
        }
        // fall through to 118
        case 118: {
    _s.push(0n);
        }
        // fall through to 119
        case 119: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 120
        case 120: {
    v_op = _s.pop();
        }
        // fall through to 121
        case 121: {
    _s.push(v_op);
        }
        // fall through to 122
        case 122: {
    _s.push("push");
        }
        // fall through to 123
        case 123: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 124
        case 124: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 141; continue; } }
        }
        // fall through to 125
        case 125: {
    _s.push(v_stack);
        }
        // fall through to 126
        case 126: {
    _s.push(v_instr);
        }
        // fall through to 127
        case 127: {
    _s.push(1n);
        }
        // fall through to 128
        case 128: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 129
        case 129: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 130
        case 130: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 131
        case 131: {
    v_stack = _s.pop();
        }
        // fall through to 132
        case 132: {
    _s.push("Pushed to stack: [");
        }
        // fall through to 133
        case 133: {
    _s.push(v_instr);
        }
        // fall through to 134
        case 134: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 135
        case 135: {
    _s.push("] stack value: ");
        }
        // fall through to 136
        case 136: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 137
        case 137: {
    _s.push(v_stack);
        }
        // fall through to 138
        case 138: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 139
        case 139: {
    omg_emit(_s.pop());
        }
        // fall through to 140
        case 140: {
    _ip = 527; continue;
        }
        // fall through to 141
        case 141: {
    _s.push(v_op);
        }
        // fall through to 142
        case 142: {
    _s.push("pop");
        }
        // fall through to 143
        case 143: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 144
        case 144: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 158; continue; } }
        }
        // fall through to 145
        case 145: {
    _s.push(v_stack);
        }
        // fall through to 146
        case 146: {
    _s.push(0n);
        }
        // fall through to 147
        case 147: {
    _s.push(v_stack);
        }
        // fall through to 148
        case 148: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 149
        case 149: {
    _s.push(1n);
        }
        // fall through to 150
        case 150: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 151
        case 151: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
        }
        // fall through to 152
        case 152: {
    v_stack = _s.pop();
        }
        // fall through to 153
        case 153: {
    _s.push("Stack popped, stack value: ");
        }
        // fall through to 154
        case 154: {
    _s.push(v_stack);
        }
        // fall through to 155
        case 155: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 156
        case 156: {
    omg_emit(_s.pop());
        }
        // fall through to 157
        case 157: {
    _ip = 527; continue;
        }
        // fall through to 158
        case 158: {
    _s.push(v_op);
        }
        // fall through to 159
        case 159: {
    _s.push("add");
        }
        // fall through to 160
        case 160: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 161
        case 161: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 218; continue; } }
        }
        // fall through to 162
        case 162: {
    _s.push(v_stack);
        }
        // fall through to 163
        case 163: {
    _s.push(v_stack);
        }
        // fall through to 164
        case 164: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 165
        case 165: {
    _s.push(1n);
        }
        // fall through to 166
        case 166: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 167
        case 167: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 168
        case 168: {
    v_rhs = _s.pop();
        }
        // fall through to 169
        case 169: {
    _s.push(v_stack);
        }
        // fall through to 170
        case 170: {
    _s.push(0n);
        }
        // fall through to 171
        case 171: {
    _s.push(v_stack);
        }
        // fall through to 172
        case 172: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 173
        case 173: {
    _s.push(1n);
        }
        // fall through to 174
        case 174: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 175
        case 175: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
        }
        // fall through to 176
        case 176: {
    v_stack = _s.pop();
        }
        // fall through to 177
        case 177: {
    _s.push(v_stack);
        }
        // fall through to 178
        case 178: {
    _s.push(v_stack);
        }
        // fall through to 179
        case 179: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 180
        case 180: {
    _s.push(1n);
        }
        // fall through to 181
        case 181: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 182
        case 182: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 183
        case 183: {
    v_lhs = _s.pop();
        }
        // fall through to 184
        case 184: {
    _s.push(v_stack);
        }
        // fall through to 185
        case 185: {
    _s.push(0n);
        }
        // fall through to 186
        case 186: {
    _s.push(v_stack);
        }
        // fall through to 187
        case 187: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 188
        case 188: {
    _s.push(1n);
        }
        // fall through to 189
        case 189: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 190
        case 190: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
        }
        // fall through to 191
        case 191: {
    v_stack = _s.pop();
        }
        // fall through to 192
        case 192: {
    _s.push(v_stack);
        }
        // fall through to 193
        case 193: {
    _s.push(v_lhs);
        }
        // fall through to 194
        case 194: {
    _s.push(v_rhs);
        }
        // fall through to 195
        case 195: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 196
        case 196: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 197
        case 197: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 198
        case 198: {
    v_stack = _s.pop();
        }
        // fall through to 199
        case 199: {
    _s.push("Added and pushed sum: [");
        }
        // fall through to 200
        case 200: {
    _s.push(v_instr);
        }
        // fall through to 201
        case 201: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 202
        case 202: {
    _s.push("[");
        }
        // fall through to 203
        case 203: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 204
        case 204: {
    _s.push(v_lhs);
        }
        // fall through to 205
        case 205: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 206
        case 206: {
    _s.push(", ");
        }
        // fall through to 207
        case 207: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 208
        case 208: {
    _s.push(v_rhs);
        }
        // fall through to 209
        case 209: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 210
        case 210: {
    _s.push("]]");
        }
        // fall through to 211
        case 211: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 212
        case 212: {
    _s.push(" Stack value: ");
        }
        // fall through to 213
        case 213: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 214
        case 214: {
    _s.push(v_stack);
        }
        // fall through to 215
        case 215: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 216
        case 216: {
    omg_emit(_s.pop());
        }
        // fall through to 217
        case 217: {
    _ip = 527; continue;
        }
        // fall through to 218
        case 218: {
    _s.push(v_op);
        }
        // fall through to 219
        case 219: {
    _s.push("sub");
        }
        // fall through to 220
        case 220: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 221
        case 221: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 278; continue; } }
        }
        // fall through to 222
        case 222: {
    _s.push(v_stack);
        }
        // fall through to 223
        case 223: {
    _s.push(v_stack);
        }
        // fall through to 224
        case 224: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 225
        case 225: {
    _s.push(1n);
        }
        // fall through to 226
        case 226: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 227
        case 227: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 228
        case 228: {
    v_rhs = _s.pop();
        }
        // fall through to 229
        case 229: {
    _s.push(v_stack);
        }
        // fall through to 230
        case 230: {
    _s.push(0n);
        }
        // fall through to 231
        case 231: {
    _s.push(v_stack);
        }
        // fall through to 232
        case 232: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 233
        case 233: {
    _s.push(1n);
        }
        // fall through to 234
        case 234: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 235
        case 235: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
        }
        // fall through to 236
        case 236: {
    v_stack = _s.pop();
        }
        // fall through to 237
        case 237: {
    _s.push(v_stack);
        }
        // fall through to 238
        case 238: {
    _s.push(v_stack);
        }
        // fall through to 239
        case 239: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 240
        case 240: {
    _s.push(1n);
        }
        // fall through to 241
        case 241: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 242
        case 242: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 243
        case 243: {
    v_lhs = _s.pop();
        }
        // fall through to 244
        case 244: {
    _s.push(v_stack);
        }
        // fall through to 245
        case 245: {
    _s.push(0n);
        }
        // fall through to 246
        case 246: {
    _s.push(v_stack);
        }
        // fall through to 247
        case 247: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 248
        case 248: {
    _s.push(1n);
        }
        // fall through to 249
        case 249: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 250
        case 250: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
        }
        // fall through to 251
        case 251: {
    v_stack = _s.pop();
        }
        // fall through to 252
        case 252: {
    _s.push(v_stack);
        }
        // fall through to 253
        case 253: {
    _s.push(v_lhs);
        }
        // fall through to 254
        case 254: {
    _s.push(v_rhs);
        }
        // fall through to 255
        case 255: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 256
        case 256: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 257
        case 257: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 258
        case 258: {
    v_stack = _s.pop();
        }
        // fall through to 259
        case 259: {
    _s.push("Subtracted and pushed difference: [");
        }
        // fall through to 260
        case 260: {
    _s.push(v_instr);
        }
        // fall through to 261
        case 261: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 262
        case 262: {
    _s.push("[");
        }
        // fall through to 263
        case 263: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 264
        case 264: {
    _s.push(v_lhs);
        }
        // fall through to 265
        case 265: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 266
        case 266: {
    _s.push(", ");
        }
        // fall through to 267
        case 267: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 268
        case 268: {
    _s.push(v_rhs);
        }
        // fall through to 269
        case 269: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 270
        case 270: {
    _s.push("]]");
        }
        // fall through to 271
        case 271: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 272
        case 272: {
    _s.push(" Stack value: ");
        }
        // fall through to 273
        case 273: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 274
        case 274: {
    _s.push(v_stack);
        }
        // fall through to 275
        case 275: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 276
        case 276: {
    omg_emit(_s.pop());
        }
        // fall through to 277
        case 277: {
    _ip = 527; continue;
        }
        // fall through to 278
        case 278: {
    _s.push(v_op);
        }
        // fall through to 279
        case 279: {
    _s.push("mul");
        }
        // fall through to 280
        case 280: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 281
        case 281: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 338; continue; } }
        }
        // fall through to 282
        case 282: {
    _s.push(v_stack);
        }
        // fall through to 283
        case 283: {
    _s.push(v_stack);
        }
        // fall through to 284
        case 284: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 285
        case 285: {
    _s.push(1n);
        }
        // fall through to 286
        case 286: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 287
        case 287: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 288
        case 288: {
    v_rhs = _s.pop();
        }
        // fall through to 289
        case 289: {
    _s.push(v_stack);
        }
        // fall through to 290
        case 290: {
    _s.push(0n);
        }
        // fall through to 291
        case 291: {
    _s.push(v_stack);
        }
        // fall through to 292
        case 292: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 293
        case 293: {
    _s.push(1n);
        }
        // fall through to 294
        case 294: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 295
        case 295: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
        }
        // fall through to 296
        case 296: {
    v_stack = _s.pop();
        }
        // fall through to 297
        case 297: {
    _s.push(v_stack);
        }
        // fall through to 298
        case 298: {
    _s.push(v_stack);
        }
        // fall through to 299
        case 299: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 300
        case 300: {
    _s.push(1n);
        }
        // fall through to 301
        case 301: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 302
        case 302: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 303
        case 303: {
    v_lhs = _s.pop();
        }
        // fall through to 304
        case 304: {
    _s.push(v_stack);
        }
        // fall through to 305
        case 305: {
    _s.push(0n);
        }
        // fall through to 306
        case 306: {
    _s.push(v_stack);
        }
        // fall through to 307
        case 307: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 308
        case 308: {
    _s.push(1n);
        }
        // fall through to 309
        case 309: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 310
        case 310: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
        }
        // fall through to 311
        case 311: {
    v_stack = _s.pop();
        }
        // fall through to 312
        case 312: {
    _s.push(v_stack);
        }
        // fall through to 313
        case 313: {
    _s.push(v_lhs);
        }
        // fall through to 314
        case 314: {
    _s.push(v_rhs);
        }
        // fall through to 315
        case 315: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_mul(_a, _b)); }
        }
        // fall through to 316
        case 316: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 317
        case 317: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 318
        case 318: {
    v_stack = _s.pop();
        }
        // fall through to 319
        case 319: {
    _s.push("Multiplied and pushed product: [");
        }
        // fall through to 320
        case 320: {
    _s.push(v_instr);
        }
        // fall through to 321
        case 321: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 322
        case 322: {
    _s.push("[");
        }
        // fall through to 323
        case 323: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 324
        case 324: {
    _s.push(v_lhs);
        }
        // fall through to 325
        case 325: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 326
        case 326: {
    _s.push(", ");
        }
        // fall through to 327
        case 327: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 328
        case 328: {
    _s.push(v_rhs);
        }
        // fall through to 329
        case 329: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 330
        case 330: {
    _s.push("]]");
        }
        // fall through to 331
        case 331: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 332
        case 332: {
    _s.push(" Stack value: ");
        }
        // fall through to 333
        case 333: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 334
        case 334: {
    _s.push(v_stack);
        }
        // fall through to 335
        case 335: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 336
        case 336: {
    omg_emit(_s.pop());
        }
        // fall through to 337
        case 337: {
    _ip = 527; continue;
        }
        // fall through to 338
        case 338: {
    _s.push(v_op);
        }
        // fall through to 339
        case 339: {
    _s.push("div");
        }
        // fall through to 340
        case 340: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 341
        case 341: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 380; continue; } }
        }
        // fall through to 342
        case 342: {
    _s.push(v_stack);
        }
        // fall through to 343
        case 343: {
    _s.push(v_stack);
        }
        // fall through to 344
        case 344: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 345
        case 345: {
    _s.push(1n);
        }
        // fall through to 346
        case 346: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 347
        case 347: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 348
        case 348: {
    v_rhs = _s.pop();
        }
        // fall through to 349
        case 349: {
    _s.push(v_stack);
        }
        // fall through to 350
        case 350: {
    _s.push(0n);
        }
        // fall through to 351
        case 351: {
    _s.push(v_stack);
        }
        // fall through to 352
        case 352: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 353
        case 353: {
    _s.push(1n);
        }
        // fall through to 354
        case 354: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 355
        case 355: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
        }
        // fall through to 356
        case 356: {
    v_stack = _s.pop();
        }
        // fall through to 357
        case 357: {
    _s.push(v_stack);
        }
        // fall through to 358
        case 358: {
    _s.push(v_stack);
        }
        // fall through to 359
        case 359: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 360
        case 360: {
    _s.push(1n);
        }
        // fall through to 361
        case 361: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 362
        case 362: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 363
        case 363: {
    v_lhs = _s.pop();
        }
        // fall through to 364
        case 364: {
    _s.push(v_stack);
        }
        // fall through to 365
        case 365: {
    _s.push(0n);
        }
        // fall through to 366
        case 366: {
    _s.push(v_stack);
        }
        // fall through to 367
        case 367: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 368
        case 368: {
    _s.push(1n);
        }
        // fall through to 369
        case 369: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 370
        case 370: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
        }
        // fall through to 371
        case 371: {
    v_stack = _s.pop();
        }
        // fall through to 372
        case 372: {
    _s.push(v_stack);
        }
        // fall through to 373
        case 373: {
    _s.push(v_lhs);
        }
        // fall through to 374
        case 374: {
    _s.push(v_rhs);
        }
        // fall through to 375
        case 375: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_div(_a, _b)); }
        }
        // fall through to 376
        case 376: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 377
        case 377: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 378
        case 378: {
    v_stack = _s.pop();
        }
        // fall through to 379
        case 379: {
    _ip = 527; continue;
        }
        // fall through to 380
        case 380: {
    _s.push(v_op);
        }
        // fall through to 381
        case 381: {
    _s.push("store");
        }
        // fall through to 382
        case 382: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 383
        case 383: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 422; continue; } }
        }
        // fall through to 384
        case 384: {
    _s.push(v_stack);
        }
        // fall through to 385
        case 385: {
    _s.push(v_stack);
        }
        // fall through to 386
        case 386: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 387
        case 387: {
    _s.push(1n);
        }
        // fall through to 388
        case 388: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 389
        case 389: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 390
        case 390: {
    v_val = _s.pop();
        }
        // fall through to 391
        case 391: {
    _s.push(v_stack);
        }
        // fall through to 392
        case 392: {
    _s.push(0n);
        }
        // fall through to 393
        case 393: {
    _s.push(v_stack);
        }
        // fall through to 394
        case 394: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 395
        case 395: {
    _s.push(1n);
        }
        // fall through to 396
        case 396: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 397
        case 397: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
        }
        // fall through to 398
        case 398: {
    v_stack = _s.pop();
        }
        // fall through to 399
        case 399: {
    _s.push(v_instr);
        }
        // fall through to 400
        case 400: {
    _s.push(1n);
        }
        // fall through to 401
        case 401: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 402
        case 402: {
    _s.push(v_val);
        }
        // fall through to 403
        case 403: {
    { const _argv = _s.splice(_s.length - 2, 2); _s.push(omg_p2(null, ..._argv)); }
        }
        // fall through to 404
        case 404: {
    v_memory = _s.pop();
        }
        // fall through to 405
        case 405: {
    _s.push("Stored value: ");
        }
        // fall through to 406
        case 406: {
    _s.push(v_val);
        }
        // fall through to 407
        case 407: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 408
        case 408: {
    _s.push(" in '");
        }
        // fall through to 409
        case 409: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 410
        case 410: {
    _s.push(v_instr);
        }
        // fall through to 411
        case 411: {
    _s.push(1n);
        }
        // fall through to 412
        case 412: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 413
        case 413: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 414
        case 414: {
    _s.push("' in memory,");
        }
        // fall through to 415
        case 415: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 416
        case 416: {
    _s.push(" stack value ");
        }
        // fall through to 417
        case 417: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 418
        case 418: {
    _s.push(v_stack);
        }
        // fall through to 419
        case 419: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 420
        case 420: {
    omg_emit(_s.pop());
        }
        // fall through to 421
        case 421: {
    _ip = 527; continue;
        }
        // fall through to 422
        case 422: {
    _s.push(v_op);
        }
        // fall through to 423
        case 423: {
    _s.push("load");
        }
        // fall through to 424
        case 424: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 425
        case 425: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 449; continue; } }
        }
        // fall through to 426
        case 426: {
    _s.push(v_stack);
        }
        // fall through to 427
        case 427: {
    _s.push(v_instr);
        }
        // fall through to 428
        case 428: {
    _s.push(1n);
        }
        // fall through to 429
        case 429: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 430
        case 430: {
    { const _argv = _s.splice(_s.length - 1, 1); _s.push(omg_p1(null, ..._argv)); }
        }
        // fall through to 431
        case 431: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
        }
        // fall through to 432
        case 432: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 433
        case 433: {
    v_stack = _s.pop();
        }
        // fall through to 434
        case 434: {
    _s.push("Loaded ");
        }
        // fall through to 435
        case 435: {
    _s.push(v_instr);
        }
        // fall through to 436
        case 436: {
    _s.push(1n);
        }
        // fall through to 437
        case 437: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 438
        case 438: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 439
        case 439: {
    _s.push(" from memory: [");
        }
        // fall through to 440
        case 440: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 441
        case 441: {
    _s.push(v_instr);
        }
        // fall through to 442
        case 442: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 443
        case 443: {
    _s.push("] stack value: ");
        }
        // fall through to 444
        case 444: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 445
        case 445: {
    _s.push(v_stack);
        }
        // fall through to 446
        case 446: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 447
        case 447: {
    omg_emit(_s.pop());
        }
        // fall through to 448
        case 448: {
    _ip = 527; continue;
        }
        // fall through to 449
        case 449: {
    _s.push(v_op);
        }
        // fall through to 450
        case 450: {
    _s.push("emit_top");
        }
        // fall through to 451
        case 451: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 452
        case 452: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 469; continue; } }
        }
        // fall through to 453
        case 453: {
    _s.push(v_stack);
        }
        // fall through to 454
        case 454: {
    _s.push(v_stack);
        }
        // fall through to 455
        case 455: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 456
        case 456: {
    _s.push(1n);
        }
        // fall through to 457
        case 457: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 458
        case 458: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 459
        case 459: {
    v_val = _s.pop();
        }
        // fall through to 460
        case 460: {
    _s.push("Top of stack: ");
        }
        // fall through to 461
        case 461: {
    _s.push(v_val);
        }
        // fall through to 462
        case 462: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 463
        case 463: {
    _s.push(" stack value: ");
        }
        // fall through to 464
        case 464: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 465
        case 465: {
    _s.push(v_stack);
        }
        // fall through to 466
        case 466: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 467
        case 467: {
    omg_emit(_s.pop());
        }
        // fall through to 468
        case 468: {
    _ip = 527; continue;
        }
        // fall through to 469
        case 469: {
    _s.push(v_op);
        }
        // fall through to 470
        case 470: {
    _s.push("jmp");
        }
        // fall through to 471
        case 471: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 472
        case 472: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 479; continue; } }
        }
        // fall through to 473
        case 473: {
    _s.push(v_instr);
        }
        // fall through to 474
        case 474: {
    _s.push(1n);
        }
        // fall through to 475
        case 475: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 476
        case 476: {
    { const _argv = _s.splice(_s.length - 1, 1); _s.push(omg_p0(null, ..._argv)); }
        }
        // fall through to 477
        case 477: {
    v_ptr = _s.pop();
        }
        // fall through to 478
        case 478: {
    _ip = 527; continue;
        }
        // fall through to 479
        case 479: {
    _s.push(v_op);
        }
        // fall through to 480
        case 480: {
    _s.push("jmp_if_nonzero");
        }
        // fall through to 481
        case 481: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 482
        case 482: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 509; continue; } }
        }
        // fall through to 483
        case 483: {
    _s.push(v_stack);
        }
        // fall through to 484
        case 484: {
    _s.push(v_stack);
        }
        // fall through to 485
        case 485: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 486
        case 486: {
    _s.push(1n);
        }
        // fall through to 487
        case 487: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 488
        case 488: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 489
        case 489: {
    v_cond = _s.pop();
        }
        // fall through to 490
        case 490: {
    _s.push(v_stack);
        }
        // fall through to 491
        case 491: {
    _s.push(0n);
        }
        // fall through to 492
        case 492: {
    _s.push(v_stack);
        }
        // fall through to 493
        case 493: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
        }
        // fall through to 494
        case 494: {
    _s.push(1n);
        }
        // fall through to 495
        case 495: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_sub(_a, _b)); }
        }
        // fall through to 496
        case 496: {
    { const _e = _s.pop(); const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_slice(_a, _b, _e)); }
        }
        // fall through to 497
        case 497: {
    v_stack = _s.pop();
        }
        // fall through to 498
        case 498: {
    _s.push(v_cond);
        }
        // fall through to 499
        case 499: {
    _s.push(0n);
        }
        // fall through to 500
        case 500: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_ne(_a, _b)); }
        }
        // fall through to 501
        case 501: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 508; continue; } }
        }
        // fall through to 502
        case 502: {
    _s.push(v_instr);
        }
        // fall through to 503
        case 503: {
    _s.push(1n);
        }
        // fall through to 504
        case 504: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
        }
        // fall through to 505
        case 505: {
    { const _argv = _s.splice(_s.length - 1, 1); _s.push(omg_p0(null, ..._argv)); }
        }
        // fall through to 506
        case 506: {
    v_ptr = _s.pop();
        }
        // fall through to 507
        case 507: {
    _ip = 508; continue;
        }
        // fall through to 508
        case 508: {
    _ip = 527; continue;
        }
        // fall through to 509
        case 509: {
    _s.push(v_op);
        }
        // fall through to 510
        case 510: {
    _s.push("label");
        }
        // fall through to 511
        case 511: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 512
        case 512: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 516; continue; } }
        }
        // fall through to 513
        case 513: {
    _s.push(0n);
        }
        // fall through to 514
        case 514: {
    v__ = _s.pop();
        }
        // fall through to 515
        case 515: {
    _ip = 527; continue;
        }
        // fall through to 516
        case 516: {
    _s.push(v_op);
        }
        // fall through to 517
        case 517: {
    _s.push("halt");
        }
        // fall through to 518
        case 518: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_eq(_a, _b)); }
        }
        // fall through to 519
        case 519: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 522; continue; } }
        }
        // fall through to 520
        case 520: {
    _ip = 528; continue;
        }
        // fall through to 521
        case 521: {
    _ip = 527; continue;
        }
        // fall through to 522
        case 522: {
    _s.push("Unknown instruction: ");
        }
        // fall through to 523
        case 523: {
    _s.push(v_op);
        }
        // fall through to 524
        case 524: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
        }
        // fall through to 525
        case 525: {
    omg_emit(_s.pop());
        }
        // fall through to 526
        case 526: {
    _ip = 528; continue;
        }
        // fall through to 527
        case 527: {
    _ip = 104; continue;
        }
        // fall through to 528
        case 528: {
    return;
        }
        // fall through to 529
        default: return;
        }
        _ip += 1;
    }
})();
} catch (_e) {
    if (_e instanceof OmgError) {
        if (typeof process !== 'undefined') { process.stderr.write(_e.kind + ': ' + _e.omgMessage + '\n'); process.exit(1); }
        else throw _e;
    } else { throw _e; }
}
