// Generated by bootstrap/src/native-js.omg from /tmp/tmp.p0qgqd5cYu/tabula_recta.omgb
// Do not edit by hand.

// omg_rt.js — runtime for OMG programs compiled to JavaScript.
//
// Mirrors bootstrap/src/omg_rt.h: provides the value coercion, the
// arithmetic/string ops, and the builtins that AOT-emitted JS calls
// into. Every program transpiled by bootstrap/src/native-js.omg
// inlines this file at the top of its .js output, so the result is
// a single self-contained JS file you can hand to `node` or run in a
// browser.
//
// Value representation:
//   ints    → JS BigInt  (so OMG's i64 semantics survive bitwise ops
//                         past 2^53; arithmetic stays exact)
//   floats  → JS Number  (OMG floats are IEEE-754 f64; same as JS)
//   strings → JS string
//   bools   → JS boolean
//   lists   → JS Array
//   dicts   → JS Map     (preserves insertion order, string keys)
//   none    → null
//   closure → JS function with .__omg_captured marker
//
// We tag the few cases JS can't distinguish on its own (Number vs
// BigInt is the only one that needs care; everything else falls out
// of `typeof`). Most ops accept either int (BigInt) or float
// (Number) and dispatch off `typeof`.

'use strict';

// === Type discrimination ===================================================

function omg_is_int(v)    { return typeof v === 'bigint'; }
function omg_is_float(v)  { return typeof v === 'number'; }
function omg_is_str(v)    { return typeof v === 'string'; }
function omg_is_bool(v)   { return typeof v === 'boolean'; }
function omg_is_list(v)   { return Array.isArray(v); }
function omg_is_dict(v)   { return v instanceof Map; }
function omg_is_none(v)   { return v === null; }
function omg_is_closure(v){ return typeof v === 'function' && v.__omg_captured !== undefined; }

// === Coercion (mirror of omg_as_int / omg_as_double in omg_rt.h) ==========

function omg_as_int(v) {
    if (typeof v === 'bigint') return v;
    if (typeof v === 'boolean') return v ? 1n : 0n;
    if (typeof v === 'number') {
        if (!Number.isFinite(v)) {
            throw new OmgError('ValueError',
                'cannot convert non-finite float to int: ' + v);
        }
        if (v < -9223372036854775808 || v > 9223372036854775807) {
            throw new OmgError('ValueError',
                'float ' + v + ' is outside the i64 range');
        }
        return BigInt(Math.trunc(v));
    }
    if (typeof v === 'string') {
        // Match Rust's Value::as_int and omg_rt.h's omg_as_int:
        // strict integer parse, no whitespace, no junk tail.
        if (!/^-?\d+$/.test(v)) {
            throw new OmgError('TypeError',
                "Invalid literal for int(): '" + v + "'");
        }
        return BigInt(v);
    }
    if (Array.isArray(v)) {
        throw new OmgError('TypeError',
            'cannot convert list to int (use length() instead)');
    }
    if (v instanceof Map) {
        throw new OmgError('TypeError', 'cannot convert dict to int');
    }
    if (v === null) {
        throw new OmgError('TypeError', 'cannot convert none to int');
    }
    if (typeof v === 'function') {
        throw new OmgError('TypeError', 'cannot convert function to int');
    }
    throw new OmgError('TypeError', 'cannot convert value to int');
}

function omg_as_float(v) {
    if (typeof v === 'number') return v;
    if (typeof v === 'bigint') return Number(v);
    if (typeof v === 'boolean') return v ? 1 : 0;
    if (typeof v === 'string') {
        const trimmed = v;
        if (!/^-?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?$/.test(trimmed)) {
            throw new OmgError('TypeError',
                "Invalid literal for float(): '" + v + "'");
        }
        return parseFloat(trimmed);
    }
    if (Array.isArray(v)) {
        throw new OmgError('TypeError', 'cannot convert list to float');
    }
    throw new OmgError('TypeError', 'cannot convert value to float');
}

function omg_truthy(v) {
    if (v === null) return false;
    if (typeof v === 'boolean') return v;
    if (typeof v === 'bigint') return v !== 0n;
    if (typeof v === 'number') return v !== 0;
    if (typeof v === 'string') return v.length > 0;
    if (Array.isArray(v)) return v.length > 0;
    if (v instanceof Map) return v.size > 0;
    return true;
}

// === Source map + call-frame stack ========================================
// Populated by the transpiled program's preamble; used by the
// traceback formatter when an uncaught OmgError surfaces at the top
// of the IIFE. Mirrors `omg_src_files` / `omg_frame_stack` in
// omg_rt.h.

let omg_src_files = [];
let omg_current_file_idx = 0;
let omg_current_line = 0;

const omg_frame_stack = [];

function omg_frame_push(name, file_idx, line) {
    omg_frame_stack.push({ name, file_idx, line });
}
function omg_frame_pop() {
    omg_frame_stack.pop();
}
// TCALL reuses the caller's slot — rewrite its display name without
// touching the call site, matching the Rust VM and the C runtime.
function omg_frame_set_top_name(name) {
    if (omg_frame_stack.length > 0) {
        omg_frame_stack[omg_frame_stack.length - 1].name = name;
    }
}

function omg_lookup_file(fi) {
    if (fi < 0 || fi >= omg_src_files.length) return '<unknown>';
    return omg_src_files[fi];
}

// Strip a `__mod_N__` mangling prefix for display, falling back to
// the input if it doesn't match the pattern.
function omg_strip_mod_prefix(name) {
    if (!name || !name.startsWith('__mod_')) return name;
    let i = 6;
    const start = i;
    while (i < name.length && name[i] >= '0' && name[i] <= '9') i++;
    if (i === start) return name;
    if (name.substr(i, 2) !== '__') return name;
    return name.substring(i + 2);
}

// Python-style traceback. Matches the layout produced by the Rust
// runtime / AOT path / OMG VM byte-for-byte — a uniform error UX
// across every implementation.
function omg_format_traceback(fullmsg) {
    let out = 'Traceback (most recent call last):\n';
    if (omg_frame_stack.length > 0) {
        const first = omg_frame_stack[0];
        out += '  File "' + omg_lookup_file(first.file_idx)
            +  '", line ' + first.line
            +  ', in <top-level>\n';
    }
    for (let i = 1; i < omg_frame_stack.length; i++) {
        const f = omg_frame_stack[i];
        out += '  File "' + omg_lookup_file(f.file_idx)
            +  '", line ' + f.line
            +  ', in ' + omg_frame_stack[i - 1].name + '\n';
    }
    const cur_fn = omg_frame_stack.length > 0
        ? omg_frame_stack[omg_frame_stack.length - 1].name
        : '<top-level>';
    out += '  File "' + omg_lookup_file(omg_current_file_idx)
        +  '", line ' + omg_current_line
        +  ', in ' + cur_fn + '\n';
    out += fullmsg;
    return out;
}

// === Errors ================================================================

class OmgError extends Error {
    constructor(kind, message) {
        super(kind + ': ' + message);
        this.kind = kind;
        this.omgMessage = message;
    }
}

function omg_panic(kind, msg) { throw new OmgError(kind, msg); }

// === to_string + emit ======================================================

// Mirrors omg_rt.h's omg_value_to_cstr / omg_print_value. Used by
// `emit` and by string concatenation when one side is non-string.
function omg_to_string(v) {
    if (v === null) return '';
    if (typeof v === 'boolean') return v ? 'true' : 'false';
    if (typeof v === 'string') return v;
    if (typeof v === 'bigint') return v.toString();
    if (typeof v === 'number') {
        // Match OMG's float printing: integer-valued floats print
        // with a trailing ".0", scientific for very small/large.
        if (Number.isFinite(v) && Number.isInteger(v) && Math.abs(v) < 1e16) {
            return v.toFixed(1);
        }
        return v.toString();
    }
    if (Array.isArray(v)) {
        return '[' + v.map(omg_to_string).join(', ') + ']';
    }
    if (v instanceof Map) {
        const parts = [];
        for (const [k, val] of v) parts.push(k + ': ' + omg_to_string(val));
        return '{' + parts.join(', ') + '}';
    }
    if (typeof v === 'function') return '<proc>';
    return String(v);
}

// emit: print to stdout with a trailing newline. In node we use
// console.log which adds the newline; for browser playgrounds we
// override _omg_write to redirect into the page.
let _omg_write = (s) => { console.log(s); };
function omg_emit(v) { _omg_write(omg_to_string(v)); }

// print: same channel, no trailing newline. Used by REPL prompts.
let _omg_print_raw = (s) => { process.stdout.write(s); };
function omg_print(v) {
    if (typeof v !== 'string') {
        omg_panic('TypeError', 'print() expects a string');
    }
    _omg_print_raw(v);
}

// === Stack helper for compound emit ========================================
// (Used by the generated code to manage operand stacks; no-op here
// since we just give programs direct access to a JS array.)

// === Arithmetic ============================================================

function omg_add(a, b) {
    if (typeof a === 'string' || typeof b === 'string') {
        return omg_to_string(a) + omg_to_string(b);
    }
    if (Array.isArray(a) && Array.isArray(b)) {
        return a.concat(b);
    }
    if (typeof a === 'number' || typeof b === 'number') {
        return omg_as_float(a) + omg_as_float(b);
    }
    return omg_as_int(a) + omg_as_int(b);
}

function omg_sub(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        return omg_as_float(a) - omg_as_float(b);
    }
    return omg_as_int(a) - omg_as_int(b);
}

function omg_mul(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        return omg_as_float(a) * omg_as_float(b);
    }
    return omg_as_int(a) * omg_as_int(b);
}

// `/`: any-float → true division (Number). int÷int → floor division
// (BigInt) to match OMG VM (`-7 / 2 == -4`).
function omg_div(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        const bd = omg_as_float(b);
        if (bd === 0) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
        return omg_as_float(a) / bd;
    }
    const x = omg_as_int(a), y = omg_as_int(b);
    if (y === 0n) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
    let q = x / y;
    if ((x % y !== 0n) && ((x < 0n) !== (y < 0n))) q -= 1n;
    return q;
}

function omg_floor_div(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        const bd = omg_as_float(b);
        if (bd === 0) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
        return Math.floor(omg_as_float(a) / bd);
    }
    const x = omg_as_int(a), y = omg_as_int(b);
    if (y === 0n) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
    let q = x / y;
    if ((x % y !== 0n) && ((x < 0n) !== (y < 0n))) q -= 1n;
    return q;
}

function omg_mod(a, b) {
    if (typeof a === 'number' || typeof b === 'number') {
        const bd = omg_as_float(b);
        if (bd === 0) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
        const ad = omg_as_float(a);
        return ad - Math.floor(ad / bd) * bd;
    }
    const x = omg_as_int(a), y = omg_as_int(b);
    if (y === 0n) omg_panic('ZeroDivisionError', 'integer division or modulo by zero');
    let r = x % y;
    if (r !== 0n && ((r < 0n) !== (y < 0n))) r += y;
    return r;
}

function omg_neg(a) {
    if (typeof a === 'number') return -a;
    return -omg_as_int(a);
}

// === Comparisons ===========================================================

function omg_values_equal(a, b) {
    // Cross-type numeric: int↔float compare by value (matches Rust).
    if ((typeof a === 'bigint' && typeof b === 'number') ||
        (typeof a === 'number' && typeof b === 'bigint')) {
        return omg_as_float(a) === omg_as_float(b);
    }
    if (typeof a !== typeof b && !(Array.isArray(a) && Array.isArray(b)) && !(a instanceof Map && b instanceof Map)) {
        return false;
    }
    if (Array.isArray(a) && Array.isArray(b)) {
        if (a.length !== b.length) return false;
        for (let i = 0; i < a.length; i++) {
            if (!omg_values_equal(a[i], b[i])) return false;
        }
        return true;
    }
    if (a instanceof Map && b instanceof Map) {
        if (a.size !== b.size) return false;
        for (const [k, v] of a) {
            if (!b.has(k)) return false;
            if (!omg_values_equal(v, b.get(k))) return false;
        }
        return true;
    }
    return a === b;
}

function omg_eq(a, b) { return omg_values_equal(a, b); }
function omg_ne(a, b) { return !omg_values_equal(a, b); }

function omg_compare(a, b) {
    if (typeof a === 'string' && typeof b === 'string') {
        if (a < b) return -1;
        if (a > b) return 1;
        return 0;
    }
    if (typeof a === 'number' || typeof b === 'number') {
        const x = omg_as_float(a), y = omg_as_float(b);
        if (x < y) return -1;
        if (x > y) return 1;
        return 0;
    }
    const x = omg_as_int(a), y = omg_as_int(b);
    if (x < y) return -1;
    if (x > y) return 1;
    return 0;
}

function omg_lt(a, b) { return omg_compare(a, b) <  0; }
function omg_le(a, b) { return omg_compare(a, b) <= 0; }
function omg_gt(a, b) { return omg_compare(a, b) >  0; }
function omg_ge(a, b) { return omg_compare(a, b) >= 0; }

// === Bitwise ===============================================================

function _reject_float(v, op) {
    if (typeof v === 'number') {
        omg_panic('TypeError', "operator '" + op + "' is not defined for floats");
    }
}

function omg_band(a, b) { _reject_float(a, '&'); _reject_float(b, '&');
                          return omg_as_int(a) & omg_as_int(b); }
function omg_bor (a, b) { _reject_float(a, '|'); _reject_float(b, '|');
                          return omg_as_int(a) | omg_as_int(b); }
function omg_bxor(a, b) { _reject_float(a, '^'); _reject_float(b, '^');
                          return omg_as_int(a) ^ omg_as_int(b); }
function omg_shl (a, b) {
    _reject_float(a, '<<'); _reject_float(b, '<<');
    const ai = omg_as_int(a), bi = omg_as_int(b);
    if (bi < 0n || bi >= 64n) omg_panic('ValueError', 'shift count out of range: ' + bi);
    return BigInt.asIntN(64, ai << bi);
}
function omg_shr (a, b) {
    _reject_float(a, '>>'); _reject_float(b, '>>');
    const ai = omg_as_int(a), bi = omg_as_int(b);
    if (bi < 0n || bi >= 64n) omg_panic('ValueError', 'shift count out of range: ' + bi);
    return ai >> bi;
}
function omg_bnot(a) { _reject_float(a, '~'); return ~omg_as_int(a); }

// === Indexing / slicing ====================================================

function _norm_idx(i, n, what) {
    let r = (i < 0) ? i + BigInt(n) : i;
    if (r < 0n || r >= BigInt(n)) {
        omg_panic('IndexError', 'index ' + i + ' out of range for length ' + n);
    }
    return Number(r);
}

function omg_index(base, idx) {
    if (typeof base === 'string') {
        if (typeof idx !== 'bigint') omg_panic('TypeError', 'string index must be int');
        const r = _norm_idx(idx, base.length, 'string');
        return base[r];
    }
    if (Array.isArray(base)) {
        if (typeof idx !== 'bigint') omg_panic('TypeError', 'list index must be int');
        const r = _norm_idx(idx, base.length, 'list');
        return base[r];
    }
    if (base instanceof Map) {
        const key = (typeof idx === 'string') ? idx : omg_to_string(idx);
        if (!base.has(key)) omg_panic('KeyError', "Key '" + key + "' not found");
        return base.get(key);
    }
    omg_panic('TypeError', 'cannot index value');
}

function omg_index_set(base, idx, val) {
    if (Array.isArray(base)) {
        if (typeof idx !== 'bigint') omg_panic('TypeError', 'list index must be int');
        const r = _norm_idx(idx, base.length, 'list');
        base[r] = val;
        return;
    }
    if (base instanceof Map) {
        const key = (typeof idx === 'string') ? idx : omg_to_string(idx);
        if (base.__omg_frozen) omg_panic('FrozenWriteError', 'Imported modules are read-only');
        base.set(key, val);
        return;
    }
    omg_panic('TypeError', 'cannot assign to index of value');
}

function omg_slice(base, start_v, end_v) {
    let n;
    if (typeof base === 'string') n = base.length;
    else if (Array.isArray(base)) n = base.length;
    else omg_panic('TypeError', 'cannot slice value');

    let start = (start_v === null) ? 0 : Number(omg_as_int(start_v));
    let end   = (end_v   === null) ? n : Number(omg_as_int(end_v));
    if (start < 0) start += n;
    if (end   < 0) end   += n;
    if (start < 0) start = 0;
    if (end   > n) end   = n;
    if (start > end) start = end;
    return base.slice(start, end);
}

function omg_attr(base, name) {
    if (base instanceof Map) {
        if (!base.has(name)) omg_panic('KeyError', "Key '" + name + "' not found");
        return base.get(name);
    }
    omg_panic('TypeError', 'cannot read attribute of value');
}

function omg_attr_set(base, name, val) {
    if (base instanceof Map) {
        if (base.__omg_frozen) omg_panic('FrozenWriteError', 'Imported modules are read-only');
        base.set(name, val);
        return;
    }
    omg_panic('TypeError', 'cannot assign attribute of value');
}

// === Builtins ==============================================================

function omg_length(v) {
    if (typeof v === 'string') {
        // OMG strings are byte-counted? Actually OMG uses code-point
        // count for strings (see omg_rt.h's omg_str_char_count). For
        // ASCII-only text these match; for now just use JS string
        // length which counts UTF-16 code units. Refine if a parity
        // test surfaces a divergence on multi-byte text.
        return BigInt(v.length);
    }
    if (Array.isArray(v)) return BigInt(v.length);
    if (v instanceof Map)  return BigInt(v.size);
    omg_panic('TypeError', 'length() expects a string, list, or dict');
}

function omg_chr(n) {
    const i = Number(omg_as_int(n));
    return String.fromCharCode(i);
}
function omg_ascii(s) {
    if (typeof s !== 'string' || s.length !== 1) {
        omg_panic('TypeError', 'ascii() expects a one-character string');
    }
    return BigInt(s.charCodeAt(0));
}
function omg_int(v)   { return omg_as_int(v); }
function omg_float(v) { return omg_as_float(v); }
function omg_floor(v) { return BigInt(Math.floor(omg_as_float(v))); }
function omg_ceil(v)  { return BigInt(Math.ceil (omg_as_float(v))); }
function omg_round(v) {
    // Banker's rounding to match Rust's f64 round-half-to-even.
    const x = omg_as_float(v);
    const r = Math.round(x);
    if (Math.abs(x - Math.trunc(x)) === 0.5 && (Math.trunc(x) & 1) === 0) {
        return BigInt(r - Math.sign(x));
    }
    return BigInt(r);
}
function omg_abs(v) {
    if (typeof v === 'bigint') return v < 0n ? -v : v;
    if (typeof v === 'number') return Math.abs(v);
    omg_panic('TypeError', 'abs() expects a number');
}
function omg_sqrt(v) { return Math.sqrt(omg_as_float(v)); }
function omg_pow(a, b) {
    if (typeof a === 'bigint' && typeof b === 'bigint' && b >= 0n) {
        return a ** b;
    }
    return Math.pow(omg_as_float(a), omg_as_float(b));
}
function omg_log(v) { return Math.log(omg_as_float(v)); }
function omg_sin(v) { return Math.sin(omg_as_float(v)); }
function omg_cos(v) { return Math.cos(omg_as_float(v)); }
function omg_tan(v) { return Math.tan(omg_as_float(v)); }

function omg_hex(n) {
    let i = omg_as_int(n);
    if (i < 0n) return '-' + (-i).toString(16);
    return i.toString(16);
}
function omg_binary(n, w) {
    let i = omg_as_int(n);
    let s;
    if (i < 0n) s = '-' + (-i).toString(2);
    else s = i.toString(2);
    if (w !== undefined) {
        const width = Number(omg_as_int(w));
        // Pad without sign if positive; if negative we leave as-is
        // (matches OMG which doesn't sign-extend the binary builtin).
        while (s.length < width) s = '0' + s;
    }
    return s;
}

function omg_freeze(d) {
    if (!(d instanceof Map)) omg_panic('TypeError', 'freeze() expects a dict');
    d.__omg_frozen = true;
    return d;
}

function omg_dict_keys(d) {
    if (!(d instanceof Map)) omg_panic('TypeError', 'dict_keys() expects a dict');
    return Array.from(d.keys());
}

function omg_string_bytes(s) {
    if (typeof s !== 'string') omg_panic('TypeError', 'string_bytes() expects a string');
    const enc = new TextEncoder();
    return Array.from(enc.encode(s)).map(b => BigInt(b));
}
function omg_bytes_to_string(bs) {
    if (!Array.isArray(bs)) omg_panic('TypeError', 'bytes_to_string() expects a list of bytes');
    const buf = new Uint8Array(bs.length);
    for (let i = 0; i < bs.length; i++) buf[i] = Number(omg_as_int(bs[i]));
    return new TextDecoder().decode(buf);
}

function omg_float_bits(s) {
    if (typeof s !== 'string') omg_panic('TypeError', 'float_bits() expects a string');
    const f = parseFloat(s);
    const buf = new ArrayBuffer(8);
    new DataView(buf).setFloat64(0, f, true);
    return new DataView(buf).getBigInt64(0, true);
}
function omg_bits_to_float(i) {
    const bi = omg_as_int(i);
    const buf = new ArrayBuffer(8);
    new DataView(buf).setBigInt64(0, bi, true);
    return new DataView(buf).getFloat64(0, true);
}

// === Exit / process control ================================================
// In node these have real implementations; in the browser the
// playground overrides them.

let _omg_exit = (code) => { if (typeof process !== 'undefined') process.exit(Number(code)); };
function omg_exit(code) { _omg_exit(omg_as_int(code)); }
function omg_exit_with_error(msg) {
    if (typeof msg !== 'string') msg = omg_to_string(msg);
    if (typeof process !== 'undefined') {
        process.stderr.write(msg + '\n');
        process.exit(1);
    } else {
        throw new OmgError('Exit', msg);
    }
}
function omg_panic_user(msg) { omg_panic('RuntimeError', omg_to_string(msg)); }

// === File I/O (node-only) =================================================
// In a browser context these all panic with a friendly message; the
// playground can override _omg_fs with a virtual FS if it wants
// programs that touch files to work.

let _omg_fs = null;
if (typeof require !== 'undefined') {
    try { _omg_fs = require('fs'); } catch (_e) { _omg_fs = null; }
}

function _need_fs(name) {
    if (!_omg_fs) {
        omg_panic('TypeError', name + '() requires file I/O (node-only)');
    }
}

function omg_read_file(path) {
    _need_fs('read_file');
    try {
        return _omg_fs.readFileSync(path, 'utf8');
    } catch (_e) {
        return false;
    }
}

function omg_file_exists(path) {
    _need_fs('file_exists');
    return _omg_fs.existsSync(path);
}

function omg_is_dir(path) {
    _need_fs('is_dir');
    try { return _omg_fs.statSync(path).isDirectory(); } catch (_e) { return false; }
}

function omg_read_dir(path) {
    _need_fs('read_dir');
    try {
        return _omg_fs.readdirSync(path).sort().filter(n => n !== '.' && n !== '..');
    } catch (_e) {
        return [];
    }
}

function omg_make_dir(path) {
    _need_fs('make_dir');
    try { _omg_fs.mkdirSync(path, { recursive: true }); return true; }
    catch (_e) { return false; }
}

// File handles for stream I/O. We implement a tiny in-memory buffer
// model (read whole file at open, write to a buffer flushed at close).
// Mode is one of r/rb/w/wb/a/ab/rb+/wb+ — matches omg_rt.h.
const _omg_handles = new Map();
let _omg_next_fd = 1;

function omg_file_open(path, mode) {
    _need_fs('file_open');
    if (typeof path !== 'string' || typeof mode !== 'string') {
        omg_panic('TypeError', 'file_open() expects path and mode');
    }
    const binary = mode.includes('b');
    const fd = _omg_next_fd++;
    let buf;
    if (mode === 'r' || mode === 'rb' || mode === 'rb+') {
        try {
            buf = _omg_fs.readFileSync(path);
        } catch (_e) {
            omg_panic('ValueError', "cannot open '" + path + "': " + _e.message);
        }
    } else if (mode === 'w' || mode === 'wb' || mode === 'wb+') {
        buf = Buffer.alloc(0);
    } else if (mode === 'a' || mode === 'ab') {
        try { buf = _omg_fs.readFileSync(path); } catch (_e) { buf = Buffer.alloc(0); }
    } else {
        omg_panic('ValueError', 'invalid file mode');
    }
    _omg_handles.set(fd, { path, mode, binary, buf, pos: (mode === 'a' || mode === 'ab') ? buf.length : 0 });
    return BigInt(fd);
}

function omg_file_read(handle) {
    const h = _omg_handles.get(Number(omg_as_int(handle)));
    if (!h) omg_panic('ValueError', 'invalid file handle');
    const slice = h.buf.subarray(h.pos);
    h.pos = h.buf.length;
    if (h.binary) return Array.from(slice).map(b => BigInt(b));
    return slice.toString('utf8');
}

function omg_file_write(handle, data) {
    const h = _omg_handles.get(Number(omg_as_int(handle)));
    if (!h) omg_panic('ValueError', 'invalid file handle');
    let chunk;
    if (h.binary) {
        if (!Array.isArray(data)) omg_panic('TypeError', 'file_write() binary handle expects list');
        chunk = Buffer.from(data.map(v => Number(omg_as_int(v))));
    } else {
        if (typeof data !== 'string') omg_panic('TypeError', 'file_write() text handle expects string');
        chunk = Buffer.from(data, 'utf8');
    }
    if (h.pos < h.buf.length) {
        // Overwrite in place, growing if needed.
        const need = h.pos + chunk.length;
        if (need > h.buf.length) {
            const nb = Buffer.alloc(need);
            h.buf.copy(nb, 0, 0, h.buf.length);
            h.buf = nb;
        }
        chunk.copy(h.buf, h.pos);
    } else {
        h.buf = Buffer.concat([h.buf, chunk]);
    }
    h.pos += chunk.length;
    return BigInt(chunk.length);
}

function omg_file_close(handle) {
    const fd = Number(omg_as_int(handle));
    const h = _omg_handles.get(fd);
    if (!h) omg_panic('ValueError', 'invalid file handle');
    if (h.mode !== 'r' && h.mode !== 'rb') {
        try { _omg_fs.writeFileSync(h.path, h.buf); }
        catch (_e) { omg_panic('ValueError', 'cannot write ' + h.path + ': ' + _e.message); }
    }
    _omg_handles.delete(fd);
    return null;
}

function omg_file_seek(handle, offset) {
    const h = _omg_handles.get(Number(omg_as_int(handle)));
    if (!h) omg_panic('ValueError', 'invalid file handle');
    const off = Number(omg_as_int(offset));
    if (off < 0) omg_panic('ValueError', 'file_seek() expects a non-negative offset');
    h.pos = off;
    return BigInt(off);
}

function omg_file_tell(handle) {
    const h = _omg_handles.get(Number(omg_as_int(handle)));
    if (!h) omg_panic('ValueError', 'invalid file handle');
    return BigInt(h.pos);
}

// === Stdin / process control (node-only) =================================

function omg_stdin_readline() {
    if (typeof require === 'undefined') return false;
    // Synchronous one-line stdin read via fs.readFileSync('/dev/stdin').
    // Cached on first call so subsequent calls walk lines from the cache.
    if (!omg_stdin_readline._buf) {
        try {
            omg_stdin_readline._buf = _omg_fs.readFileSync(0, 'utf8');
            omg_stdin_readline._pos = 0;
        } catch (_e) {
            omg_stdin_readline._buf = '';
            omg_stdin_readline._pos = 0;
        }
    }
    const buf = omg_stdin_readline._buf;
    let pos = omg_stdin_readline._pos;
    if (pos >= buf.length) return false;
    const nl = buf.indexOf('\n', pos);
    let line;
    if (nl < 0) { line = buf.slice(pos); omg_stdin_readline._pos = buf.length; }
    else { line = buf.slice(pos, nl); omg_stdin_readline._pos = nl + 1; }
    if (line.endsWith('\r')) line = line.slice(0, -1);
    return line;
}

function omg_stdin_read() {
    if (typeof require === 'undefined') return '';
    try { return _omg_fs.readFileSync(0, 'utf8'); }
    catch (_e) { return ''; }
}

function omg_stdin_read_bytes() {
    if (typeof require === 'undefined') return [];
    try { return Array.from(_omg_fs.readFileSync(0)).map(b => BigInt(b)); }
    catch (_e) { return []; }
}

function omg_subprocess(argv) {
    if (typeof require === 'undefined') {
        omg_panic('TypeError', 'subprocess() requires node');
    }
    const { spawnSync } = require('child_process');
    if (!Array.isArray(argv)) omg_panic('TypeError', 'subprocess() expects a list');
    const cmd = argv[0];
    const args = argv.slice(1);
    const r = spawnSync(cmd, args, { stdio: 'inherit' });
    if (r.error) omg_panic('ValueError', 'subprocess: ' + r.error.message);
    return BigInt(r.status === null ? 128 + (r.signal === 'SIGINT' ? 2 : 1) : r.status);
}

function omg_getpid() {
    return BigInt(typeof process !== 'undefined' ? process.pid : 0);
}

function omg_executable_path() {
    return typeof process !== 'undefined' ? process.argv[0] : false;
}

// === call_builtin: dynamic dispatch =======================================
// Used by some advanced features (the OMG-in-OMG interpreter, error
// helpers). Maps name → handler.

const _omg_builtins = {
    chr: omg_chr,
    ascii: omg_ascii,
    int: omg_int,
    float: omg_float,
    floor: omg_floor,
    ceil: omg_ceil,
    round: omg_round,
    abs: omg_abs,
    sqrt: omg_sqrt,
    pow: omg_pow,
    log: omg_log,
    sin: omg_sin,
    cos: omg_cos,
    tan: omg_tan,
    hex: omg_hex,
    binary: omg_binary,
    length: omg_length,
    freeze: omg_freeze,
    dict_keys: omg_dict_keys,
    string_bytes: omg_string_bytes,
    bytes_to_string: omg_bytes_to_string,
    float_bits: omg_float_bits,
    bits_to_float: omg_bits_to_float,
    panic: omg_panic_user,
    raise: omg_panic_user,
    exit: omg_exit,
    exit_with_error: omg_exit_with_error,
    print: omg_print,
    read_file: omg_read_file,
    file_open: omg_file_open,
    file_read: omg_file_read,
    file_write: omg_file_write,
    file_close: omg_file_close,
    file_seek: omg_file_seek,
    file_tell: omg_file_tell,
    file_exists: omg_file_exists,
    is_dir: omg_is_dir,
    read_dir: omg_read_dir,
    make_dir: omg_make_dir,
    stdin_readline: omg_stdin_readline,
    stdin_read: omg_stdin_read,
    stdin_read_bytes: omg_stdin_read_bytes,
    subprocess: omg_subprocess,
    getpid: omg_getpid,
    executable_path: omg_executable_path,
};

function omg_call_builtin(name, args) {
    const fn = _omg_builtins[name];
    if (!fn) omg_panic('TypeError', 'unknown builtin: ' + name);
    return fn(...args);
}
_omg_builtins.call_builtin = omg_call_builtin;

// === Closure helper =======================================================

function omg_closure(fn, captured, name) {
    const wrapped = (...args) => fn(captured, ...args);
    wrapped.__omg_captured = captured;
    // Bare source name (no `__mod_N__` mangling) for traceback
    // rendering when this closure is invoked via CALL_VALUE.
    wrapped.__omg_name = name || '<closure>';
    return wrapped;
}

// String-named function table. Populated by the program preamble
// after every top-level MAKE_FUNC, so that CALL_VALUE on a string
// (which is what import-module dispatch produces) can resolve it.
const omg_func_table = new Map();
function omg_lookup_fn(name) {
    const fn = omg_func_table.get(name);
    if (!fn) omg_panic('UndefinedIdentError', name);
    return fn;
}

// Default-injected globals. Programs may shadow these.
// `args` and friends are `let` so the page can override them before
// re-eval-ing the playground bundle on each Run click. The `v_*`
// aliases match what native-js.omg's `js_var()` emits for source-
// level references (LOAD "args" → `v_args`).
let args = (typeof process !== 'undefined') ? process.argv.slice(1) : [];
let module_file = '';
let current_dir = (typeof process !== 'undefined') ? process.cwd() : '/';
let v_args = args;
let v_module_file = module_file;
let v_current_dir = current_dir;

// === Program ==============================================================

omg_src_files = [
    "/home/chris/workspace/omglang/examples/tabula_recta.omg",
];
omg_current_file_idx = 0;

let v_alphabet;
let v_shift;
let v_tabula_recta;
let v_table;
let v_i;

function omg_p0(_captured) {
    let v_i;
    let v_result;
    const _s = [];
    omg_current_file_idx = 0;
    let _ip = 22;
    let _eh = [];
    while (true) {
        try {
            switch (_ip) {
            case 22: {
                omg_current_line = 5;
    _s.push(0n);
            }
            // fall through to 23
            case 23: {
    v_i = _s.pop();
            }
            // fall through to 24
            case 24: {
                omg_current_line = 6;
    { const _arr = _s.splice(_s.length - 0, 0); _s.push(_arr); }
            }
            // fall through to 25
            case 25: {
    v_result = _s.pop();
            }
            // fall through to 26
            case 26: {
                omg_current_line = 7;
    _s.push(v_i);
            }
            // fall through to 27
            case 27: {
    _s.push(26n);
            }
            // fall through to 28
            case 28: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
            }
            // fall through to 29
            case 29: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 43; continue; } }
            }
            // fall through to 30
            case 30: {
                omg_current_line = 8;
    _s.push(v_result);
            }
            // fall through to 31
            case 31: {
    _s.push(65n);
            }
            // fall through to 32
            case 32: {
    _s.push(v_i);
            }
            // fall through to 33
            case 33: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 34
            case 34: {
    { const _a = _s.pop(); _s.push(omg_chr(_a)); }
            }
            // fall through to 35
            case 35: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
            }
            // fall through to 36
            case 36: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 37
            case 37: {
    v_result = _s.pop();
            }
            // fall through to 38
            case 38: {
                omg_current_line = 9;
    _s.push(v_i);
            }
            // fall through to 39
            case 39: {
    _s.push(1n);
            }
            // fall through to 40
            case 40: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 41
            case 41: {
    v_i = _s.pop();
            }
            // fall through to 42
            case 42: {
    _ip = 26; continue;
            }
            // fall through to 43
            case 43: {
                omg_current_line = 11;
    _s.push(v_result);
            }
            // fall through to 44
            case 44: {
    return _s.pop();
            }
            // fall through to 45
            case 45: {
    _s.push(null);
            }
            // fall through to 46
            case 46: {
    return _s.pop();
            }
            // fall through to 47
            default: return;
            }
            _ip += 1;
        } catch (_e) {
            if (_e instanceof OmgError && _eh.length > 0) {
                const _entry = _eh.pop();
                _ip = _entry[0];
                while (omg_frame_stack.length > _entry[1]) { omg_frame_pop(); }
                _s.length = 0;
                _s.push(_e.kind + ': ' + _e.omgMessage);
            } else { throw _e; }
        }
    }
}

function omg_p1(_captured, v_a_list, v_n) {
    let v_i;
    let v_result;
    let v_len;
    let v_shifted;
    const _s = [];
    omg_current_file_idx = 0;
    let _ip = 47;
    let _eh = [];
    while (true) {
        try {
            switch (_ip) {
            case 47: {
                omg_current_line = 16;
    _s.push(0n);
            }
            // fall through to 48
            case 48: {
    v_i = _s.pop();
            }
            // fall through to 49
            case 49: {
                omg_current_line = 17;
    { const _arr = _s.splice(_s.length - 0, 0); _s.push(_arr); }
            }
            // fall through to 50
            case 50: {
    v_result = _s.pop();
            }
            // fall through to 51
            case 51: {
                omg_current_line = 18;
    _s.push(v_a_list);
            }
            // fall through to 52
            case 52: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
            }
            // fall through to 53
            case 53: {
    v_len = _s.pop();
            }
            // fall through to 54
            case 54: {
                omg_current_line = 19;
    { const _arr = _s.splice(_s.length - 0, 0); _s.push(_arr); }
            }
            // fall through to 55
            case 55: {
    v_shifted = _s.pop();
            }
            // fall through to 56
            case 56: {
                omg_current_line = 20;
    _s.push(v_i);
            }
            // fall through to 57
            case 57: {
    _s.push(v_len);
            }
            // fall through to 58
            case 58: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
            }
            // fall through to 59
            case 59: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 78; continue; } }
            }
            // fall through to 60
            case 60: {
                omg_current_line = 21;
    _s.push(v_a_list);
            }
            // fall through to 61
            case 61: {
    _s.push(v_i);
            }
            // fall through to 62
            case 62: {
    _s.push(v_n);
            }
            // fall through to 63
            case 63: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 64
            case 64: {
    _s.push(v_len);
            }
            // fall through to 65
            case 65: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_mod(_a, _b)); }
            }
            // fall through to 66
            case 66: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 67
            case 67: {
    v_shifted = _s.pop();
            }
            // fall through to 68
            case 68: {
                omg_current_line = 22;
    _s.push(v_result);
            }
            // fall through to 69
            case 69: {
    _s.push(v_shifted);
            }
            // fall through to 70
            case 70: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
            }
            // fall through to 71
            case 71: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 72
            case 72: {
    v_result = _s.pop();
            }
            // fall through to 73
            case 73: {
                omg_current_line = 23;
    _s.push(v_i);
            }
            // fall through to 74
            case 74: {
    _s.push(1n);
            }
            // fall through to 75
            case 75: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 76
            case 76: {
    v_i = _s.pop();
            }
            // fall through to 77
            case 77: {
    _ip = 56; continue;
            }
            // fall through to 78
            case 78: {
                omg_current_line = 25;
    _s.push(v_result);
            }
            // fall through to 79
            case 79: {
    return _s.pop();
            }
            // fall through to 80
            case 80: {
    _s.push(null);
            }
            // fall through to 81
            case 81: {
    return _s.pop();
            }
            // fall through to 82
            default: return;
            }
            _ip += 1;
        } catch (_e) {
            if (_e instanceof OmgError && _eh.length > 0) {
                const _entry = _eh.pop();
                _ip = _entry[0];
                while (omg_frame_stack.length > _entry[1]) { omg_frame_pop(); }
                _s.length = 0;
                _s.push(_e.kind + ': ' + _e.omgMessage);
            } else { throw _e; }
        }
    }
}

function omg_p2(_captured) {
    let v_i;
    let v_base;
    let v_result;
    const _s = [];
    omg_current_file_idx = 0;
    let _ip = 82;
    let _eh = [];
    while (true) {
        try {
            switch (_ip) {
            case 82: {
                omg_current_line = 30;
    _s.push(0n);
            }
            // fall through to 83
            case 83: {
    v_i = _s.pop();
            }
            // fall through to 84
            case 84: {
                omg_current_line = 31;
    { const _argv = _s.splice(_s.length - 0, 0); omg_frame_push("alphabet", omg_current_file_idx, omg_current_line); const _rv = omg_p0(null, ..._argv); omg_frame_pop(); _s.push(_rv); }
            }
            // fall through to 85
            case 85: {
    v_base = _s.pop();
            }
            // fall through to 86
            case 86: {
                omg_current_line = 32;
    { const _arr = _s.splice(_s.length - 0, 0); _s.push(_arr); }
            }
            // fall through to 87
            case 87: {
    v_result = _s.pop();
            }
            // fall through to 88
            case 88: {
                omg_current_line = 33;
    _s.push(v_i);
            }
            // fall through to 89
            case 89: {
    _s.push(26n);
            }
            // fall through to 90
            case 90: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
            }
            // fall through to 91
            case 91: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 104; continue; } }
            }
            // fall through to 92
            case 92: {
                omg_current_line = 34;
    _s.push(v_result);
            }
            // fall through to 93
            case 93: {
    _s.push(v_base);
            }
            // fall through to 94
            case 94: {
    _s.push(v_i);
            }
            // fall through to 95
            case 95: {
    { const _argv = _s.splice(_s.length - 2, 2); omg_frame_push("shift", omg_current_file_idx, omg_current_line); const _rv = omg_p1(null, ..._argv); omg_frame_pop(); _s.push(_rv); }
            }
            // fall through to 96
            case 96: {
    { const _arr = _s.splice(_s.length - 1, 1); _s.push(_arr); }
            }
            // fall through to 97
            case 97: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 98
            case 98: {
    v_result = _s.pop();
            }
            // fall through to 99
            case 99: {
                omg_current_line = 35;
    _s.push(v_i);
            }
            // fall through to 100
            case 100: {
    _s.push(1n);
            }
            // fall through to 101
            case 101: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 102
            case 102: {
    v_i = _s.pop();
            }
            // fall through to 103
            case 103: {
    _ip = 88; continue;
            }
            // fall through to 104
            case 104: {
                omg_current_line = 37;
    _s.push(v_result);
            }
            // fall through to 105
            case 105: {
    return _s.pop();
            }
            // fall through to 106
            case 106: {
    _s.push(null);
            }
            // fall through to 107
            case 107: {
    return _s.pop();
            }
            // fall through to 108
            default: return;
            }
            _ip += 1;
        } catch (_e) {
            if (_e instanceof OmgError && _eh.length > 0) {
                const _entry = _eh.pop();
                _ip = _entry[0];
                while (omg_frame_stack.length > _entry[1]) { omg_frame_pop(); }
                _s.length = 0;
                _s.push(_e.kind + ': ' + _e.omgMessage);
            } else { throw _e; }
        }
    }
}

omg_func_table.set("alphabet", omg_p0);
omg_func_table.set("shift", omg_p1);
omg_func_table.set("tabula_recta", omg_p2);

try {
(function _omg_main() {
    const _s = [];
    let _ip = 0;
    let _eh = [];
    while (true) {
        try {
            switch (_ip) {
            case 0: {
                omg_current_line = 11;
    {
        const _cap = new Map();
        v_alphabet = omg_closure(omg_p0, _cap, "alphabet");
    }
            }
            // fall through to 1
            case 1: {
                omg_current_line = 25;
    {
        const _cap = new Map();
        v_shift = omg_closure(omg_p1, _cap, "shift");
    }
            }
            // fall through to 2
            case 2: {
                omg_current_line = 37;
    {
        const _cap = new Map();
        v_tabula_recta = omg_closure(omg_p2, _cap, "tabula_recta");
    }
            }
            // fall through to 3
            case 3: {
                omg_current_line = 41;
    { const _argv = _s.splice(_s.length - 0, 0); omg_frame_push("tabula_recta", omg_current_file_idx, omg_current_line); const _rv = omg_p2(null, ..._argv); omg_frame_pop(); _s.push(_rv); }
            }
            // fall through to 4
            case 4: {
    v_table = _s.pop();
            }
            // fall through to 5
            case 5: {
                omg_current_line = 42;
    _s.push(0n);
            }
            // fall through to 6
            case 6: {
    v_i = _s.pop();
            }
            // fall through to 7
            case 7: {
                omg_current_line = 43;
    _s.push(v_i);
            }
            // fall through to 8
            case 8: {
    _s.push(v_table);
            }
            // fall through to 9
            case 9: {
    { const _a = _s.pop(); _s.push(omg_length(_a)); }
            }
            // fall through to 10
            case 10: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_lt(_a, _b)); }
            }
            // fall through to 11
            case 11: {
    { const _c = _s.pop(); if (!omg_truthy(_c)) { _ip = 21; continue; } }
            }
            // fall through to 12
            case 12: {
                omg_current_line = 44;
    _s.push(v_table);
            }
            // fall through to 13
            case 13: {
    _s.push(v_i);
            }
            // fall through to 14
            case 14: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_index(_a, _b)); }
            }
            // fall through to 15
            case 15: {
    omg_emit(_s.pop());
            }
            // fall through to 16
            case 16: {
                omg_current_line = 45;
    _s.push(v_i);
            }
            // fall through to 17
            case 17: {
    _s.push(1n);
            }
            // fall through to 18
            case 18: {
    { const _b = _s.pop(); const _a = _s.pop(); _s.push(omg_add(_a, _b)); }
            }
            // fall through to 19
            case 19: {
    v_i = _s.pop();
            }
            // fall through to 20
            case 20: {
    _ip = 7; continue;
            }
            // fall through to 21
            case 21: {
    return;
            }
            // fall through to 22
            default: return;
            }
            _ip += 1;
        } catch (_e) {
            if (_e instanceof OmgError && _eh.length > 0) {
                const _entry = _eh.pop();
                _ip = _entry[0];
                while (omg_frame_stack.length > _entry[1]) { omg_frame_pop(); }
                _s.length = 0;
                _s.push(_e.kind + ': ' + _e.omgMessage);
            } else { throw _e; }
        }
    }
})();
} catch (_e) {
    if (_e instanceof OmgError) {
        const _full = _e.kind + ': ' + _e.omgMessage;
        const _trace = omg_format_traceback(_full);
        if (typeof process !== 'undefined') { process.stderr.write(_trace + '\n'); process.exit(1); }
        else { _e.message = _trace; throw _e; }
    } else { throw _e; }
}
